### ISSUE TITLE
pull images or starting containers from registry hosted images

### ISSUE THREAD

**Issue by windowsrefund** [swipely/docker-api#108]
Hello,

I've been able to build images and push them over to quay.io 

Now I'd like to start containers from those images on another Docker instance. I'd think my approach would be
1. Redefine Docker.url (point to the new Docker instance)
2. pull images down from registry
3. Start containers

If my approach is sane, how would #pull be used via the API?

**Comment by mrdziuban** [comment]
I know this issue is closed, but I'm having a similar issue trying to pull an image from my Docker Hub account. I created [this public test repo](https://hub.docker.com/r/mrdziuban/testrepo/) to demonstrate the issue:

```
Docker::Image.create(
  'fromImage' => 'mrdziuban/testrepo`,
  'tag' => 'latest'
)
```

This is the JSON returned from the API:

```
[{"status"=>"Pulling repository mrdziuban/testrepo"}, {"errorDetail"=>{"message"=>"Repository not found"}, "error"=>"Repository not found"}]
```

And the error is:

```
Must have id, got: {"id"=>nil, :headers=>{"X-Registry-Auth"=>"eyJzZXJ2ZXJhZGRyZXNzIjoiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIiwidXNlcm5hbWUiOiJtcmR6aXViYW4iLCJwYXNzd29yZCI6ImxvY2FseXRpY3MiLCJlbWFpbCI6Im1keml1YmFuQGxvY2FseXRpY3MuY29tIn0="}}
```
