### ISSUE TITLE
Using container.copy to insert content of a file into a string

### ISSUE THREAD

**Issue by msf1013** [swipely/docker-api#233]
Hello! I am using the following method (which I found in stackoverflow) to redirect the stdout into a variable. 

``` ruby
def with_captured_stdout
  begin
    old_stdout = $stdout
    $stdout = StringIO.new('','w')
    yield
    $stdout.string
  ensure
    $stdout = old_stdout
  end
end
```

In conjuction with the container.copy('/etc/hosts') { |chunk| puts chunk } function, I am retrieving the content of a text file ("Hello") in a string with the following code:

``` ruby
str = with_captured_stdout { sss.copy('/etc/output.txt') { |chunk| puts chunk }  }
```

Nonetheless, printing the string results in the following output

``` terminal
irb(main):018:0> print str
output.txt0100644000000000000000000000000612442645754011357 0ustar0000000000000000Hello

=> nil
```

As I can see in the documentation, .copy exports the contents as tars. Could you suggest me how to use .copy to insert the content of a text file in the container into a string?

**Comment by rosskevin** [comment]
This worked, note the very important error handling, as null file names (result of something following too long of a file name) was wiping out the parent dir permissions.

```ruby
      def extract_files(container, from = '/project/target', to = '.')
        # or something like
        tar_stringio = StringIO.new
        container.copy(from) do |chunk|
          tar_stringio.write(chunk)
          # puts "#{chunk}"
        end

        tar_stringio.rewind

        input = Archive::Tar::Minitar::Input.new(tar_stringio)
        input.each { |entry|

          # Need to check the file name length to prevent some very bad things from happening.
          if entry.full_name.length > 255
            puts "ERROR - file name length is > 255 characters: #{entry.full_name}"
          elsif entry.full_name.length <= 0
            puts "ERROR - file name length is too small: #{entry.full_name}"
          else
            puts "Extracting #{entry.full_name}"
            input.extract_entry(to, entry)
          end
        }
      end
```

**Comment by rosskevin** [comment]
If there were a wiki, I'd put this in it...

**Comment by tlunter** [comment]
This seems to be more in the scope of `Archive::Tar::Minitar`'s wiki.  Since the issues are searchable, I think it's fine to leave here.  If we get more people asking how to work with tars from docker, we can throw something small in the README.  One thing to note is most ruby tar libraries aren't perfect and most don't support the PAX extended headers that docker will export.
