### ISSUE TITLE
How to avoid echoing the "input command"  when attaching container.

### ISSUE THREAD

**Issue by cheyang** [swipely/docker-api#238]
I'm using the following code to simulate the "attach" behavior of docker
container.attach(:stdin => STDIN,  :tty => true){|stream|
print "#{stream}"
 }
It works fine except a small problem:

[root@docker ~]# ruby /test_docker.rb
pwd
pwd
/
root@1444cc0cd69c:/# ls
ls
bin   dev  home  lib64  mnt  proc  run   srv  tmp  var
boot  etc  lib   media  opt  root  sbin  sys  usr
root@1444cc0cd69c:/# exit
exit

You can see when I input "ls" then click enter. It will output "ls" first, then output the expected result. Are there any ways to avoid this? I hope to filter the echo. thanks very much.

**Comment by tlunter** [comment]
This seems to be more of a docker/terminal issue, with inputing information into the stdin and docker repeating to stdout.  If you find a solution, feel free to share, but you're more likely going to find a solution on the main docker project.
