### ISSUE TITLE
see streaming output of image build?

### ISSUE THREAD

**Issue by dtenenba** [swipely/docker-api#242]
Is there a way to see the output of `Image#build...` as it is happening, the way I could if I ran `docker build` from the command line? Like, maybe there's a way to use an Excon streaming response with the docker-api to facilitate this? Some of my image builds can take a long time and I'd like to know that something is actually happening rather than have to wait a long time only to find that the code is hung or the daemon is not responding, or something. The daemon itself doesn't seem to log the information I'm looking for (which is essentially the same stdout/stderr I would see if I ran `docker build` from the command line). I'm actually running ` Docker::Image#build_from_dir` right now and it has just been sitting there for a very long time. I expect this build to take some time but it would be good to know what is going on...is this possible?

**Comment by dtenenba** [comment]
Sorry, just saw this:
"If a block is passed, chunks of output produced by Docker will be passed to that block."

**Comment by wesm-outreach** [comment]
This seems broken.

Repro
```
Dir.mktmpdir do |dir|
        dockerfile = <<EOF
FROM debian:jessie
LABEL image.test=true
RUN sleep 5
RUN sleep 5
EOF

  File.write(File.join(dir, 'Dockerfile'), dockerfile)

  ::Docker::Image.build_from_dir(docker_build_path) do |v|
    puts('*** LOG STATEMENT ***')
    puts(v)

    if (log = JSON.parse(v)) && log.has_key?('stream')
      $stdout.puts log['stream']
    end
end
```

Output:

```
*** LOG STATEMENT ***
{"stream":"Step 1/4 : FROM debian:jessie\n"}
{"stream":" ---\u003e 40aa6d4339d4\n"}
{"stream":"Step 2/4 : LABEL image.test true\n"}
{"stream":" ---\u003e Using cache\n"}
{"stream":" ---\u003e 2d49e905e1a9\n"}
{"stream":"Step 3/4 : RUN sleep 5\n"}
{"stream":" ---\u003e Running in 70444a679077\n"}
{"stream":" ---\u003e 211887f948b9\n"}
{"stream":"Removing intermediate container 70444a679077\n"}
{"stream":"Step 4/4 : RUN sleep 5\n"}
{"stream":" ---\u003e Running in 19772dfb215c\n"}
{"stream":" ---\u003e 02b54986a8e0\n"}
{"stream":"Removing intermediate container 19772dfb215c\n"}
{"stream":"Successfully built 02b54986a8e0\n"}
```

First, I expect to see `*** LOG STATEMENT ***` once per line or on a regular basis.

Second, this JSON is invalid. and I get `JSON::ParserError:`
