### ISSUE TITLE
Listing all containers with filters

### ISSUE THREAD

**Issue by msf1013** [swipely/docker-api#246]
Is there a way to use ```Docker::Container.all(:all => true)``` in order to achieve ```docker ps -a --filter 'status=exited'```? Listing all containers that have been exited.

**Comment by assimovt** [comment]
Since [Docker API](https://docs.docker.com/reference/api/docker_remote_api_v1.15/#list-containers) expects "JSON encoded value of the filters" you can do it as follows:

    Docker::Container.all(all: true, filters: { status: ["exited"] }.to_json)

The above will filter all containers by status ```exited```.

**Comment by tlunter** [comment]
Thanks for the help @assimovt

**Comment by msf1013** [comment]
Thanks for the help too @assimovt, excuse me for not replying back this time @tlunter.
