### ISSUE TITLE
VersionError

### ISSUE THREAD

**Issue by fwidtmann** [swipely/docker-api#247]
hi, 

with version 1.17 i get Docker::Error::VersionError: Expected API Version 1.15
if i downgrade the docker-api gem to 1.15, i get Docker::Error::VersionError: Expected API Version 1.12

can you help me?

btw. im on mac osx with boot2docker version 1.4.1, ruby 2.1.1 and rails 4.2.0

**Comment by tlunter** [comment]
Sorry about the confusing error message.  I think docker is complaining that the endpoint version that our gem is hitting, is behind the latest version supported by docker.  The error seems to imply that you should change the version of docker-api, but that's not the case!  I haven't seen this error yet myself, can you provide example code that'll hit this error?  Also, what is the output of `docker version` for the server?

**Comment by fwidtmann** [comment]
i created a new rails app, added your gem and called Docker.validate_version! in the console.
all other methods get a timeout.

Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): darwin/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8

**Comment by kirs** [comment]
I have the same issue actually.

**Comment by kirs** [comment]
Have a look on this https://github.com/swipely/docker-api/pull/249
