### ISSUE TITLE
Method create_dir_tar is not thread safe

### ISSUE THREAD

**Issue by joshfng** [swipely/docker-api#248]
When creating many Docker images from within sidekiq a race occurs if two sidekiq threads are trying to build a Docker image from a directory containing a Dockerfile. If sidekiq thread 1 calls `Docker::Image.create_from_dir` and it doesn't finish before sidekiq 2 thread calls `Docker::Image.create_from_dir` it will no longer be working from the directory it expected because `create_dir_tar` has called `FileUtils.cd(directory)` and has not completed taring the directory yet and called `FileUtils.cd(cwd)` to back out.

**Comment by tlunter** [comment]
@joshfng v1.20.0 now supports thread safe `create_dir_tar`.
