### ISSUE TITLE
Dealing with multiple docker APIs

### ISSUE THREAD

**Issue by daviddavis** [swipely/docker-api#253]
We have an application that is made to connect to multiple running docker instances. The problem with docker-api is that it uses a singleton to store the Docker api info so that for each request we have to call Docker.url, Docker.authenticate, etc. This is not ideal nor thread-safe. Is there a better way to deal with this? Was expecting something like:

```ruby
remote = Docker.new(:url => "http://example.com", :username => "blah", :password => "test")
local = Docker.new(:url => "unix:///var/docker.sock")
```

**Comment by nahiluhmot** [comment]
Creating connections to multiple Docker servers is [documented in the README](https://github.com/swipely/docker-api#connecting-to-multiple-servers), and every class method supports setting a custom Docker connection (see [this example](https://github.com/swipely/docker-api/blob/master/lib/docker/image.rb#L105)).

Does this solve you problem?

**Comment by daviddavis** [comment]
Yes, I'm an idiot. :+1:
