### ISSUE TITLE
Mount a Host Directory as a Data Volume?

### ISSUE THREAD

**Issue by p8952** [swipely/docker-api#256]
I'm looking to mount a host directory as a data volume as described [here](https://docs.docker.com/userguide/dockervolumes/)

For example:

    docker run -v /tmp:/tmp ubuntu:14.04 touch /tmp/foobar
    file /tmp/foobar
    /tmp/foobar: empty

I've seen #101 but this only seems to work for data volumes, not host directories. Is it possible to use docker-api to mount a data volume from the host?

**Comment by tlunter** [comment]
@p8952 
That is exactly what https://github.com/swipely/dockly/pull/33/files#diff-baf7759fc25a0848e4c887f48603125eR39 and https://github.com/swipely/dockly/pull/33/files#diff-baf7759fc25a0848e4c887f48603125eR42 are doing.  You should be able to just do:

```
container = Docker::Container.create(
  'Image' => 'ubuntu:14.04',
  'Cmd' => ['/bin/bash', '-c', 'touch /tmp/foobar; file /tmp/foobar'],
  'Volumes' => {
    '/tmp' => { '/tmp' => 'rw' }
  }
)
container.start('Binds' => '/tmp:/tmp')
```

Through testing, it appears the `Volumes` key-value should even be needed, but that is all they show on the Remote API docs.  `Binds` is definitely needed though.

**Comment by p8952** [comment]
@tlunter That's doing exactly what I want. Thank you, I completed missed the bind part of that PR.
