### ISSUE TITLE
Can't create named containers

### ISSUE THREAD

**Issue by trademesh** [swipely/docker-api#265]
Hi guys,

I am trying to create a Container with a certain name. I've tried several ways but had no luck yet.
I found some "strange" code within the container.rb of docker-api

    def self.create(opts = {}, conn = Docker.connection)
    name = opts.delete('name')
    query = {}
    query['name'] = name if name

It seems like it is deleting the name from a create command. Does this make any sense?

Best regards,
trademesh

**Comment by tlunter** [comment]
We delete the `name` parameter, and pass it in the query parameters.

You'll see [here](http://docs.docker.com/reference/api/docker_remote_api_v1.17/#create-a-container), that `name` is the only parameter passed in the query.

Make sure you're passing the name in as string, or else it won't get passed in the query parameter!
