### ISSUE TITLE
Accessing API over TLS/SSL

### ISSUE THREAD

**Issue by marto** [swipely/docker-api#267]
We run our docker daemon over SSL as described [here](https://docs.docker.com/articles/https/). 

The equivalent curl command would be:
```
curl https://$DOCKER_HOST/images/json \
  --cert ~/.docker/cert.pem \
  --key ~/.docker/key.pem \
  --cacert ~/.docker/ca.pem
```

The documentation doesn't have an example of how one would connect to the API using SSL mutual authetication, but from the looks of it, as it's based on excon it should be possible. I'm going through the excon documentation but it's hard work. Would it be possible to put it up and example in the documentation?

If I manage to figure it out I'll post the answer...

**Comment by tlunter** [comment]
If you set an environment variable of `DOCKER_CERT_PATH`, `docker-api` will automatically use SSL for you: https://github.com/swipely/docker-api/blob/master/lib/docker.rb#L43-L49

Let me know if that works!

**Comment by marto** [comment]
Works perfectly. Thanks for the tip. Is it worthwhile adding it to the README.md?

**Comment by tlunter** [comment]
Sure, I'll add something.  Usually this is handled for people using boot2docker, but I'll add something for those who are using SSL without boot2docker!

**Comment by tlunter** [comment]
This has been added to the README.
