### ISSUE TITLE
Docker::Image.build_from_dir breaks caching

### ISSUE THREAD

**Issue by errm** [swipely/docker-api#269]
The mtime on all the files is updated and thus breaks caching.

**Comment by errm** [comment]
Looks to be related to this line in the rubygems tar writer https://github.com/rubygems/rubygems/blob/800f2e63bc6174b5b4dea5528110b09d89fe3dd1/lib/rubygems/package/tar_writer.rb#L127

**Comment by randywallace** [comment]
have you tried the util function included with this rubygem for creating a tar?

This works for me just fine and uses the cache:

```ruby
img = Docker::Image.build_from_tar(Docker::Util.create_dir_tar('.')) do |chunk|
  puts JSON.parse(chunk)['stream']
end

img.tag 'repo' => 'test', 'tag' => 'test', 'force' => true

puts img.inspect
```

Here is my very simple Dockerfile used to demonstrate this (I tested this by running it a few times):

```
Step 0 : FROM ubuntu:14.04
 ---> d0955f21bf24
Step 1 : ADD lib/ /startup-functions
 ---> Using cache
 ---> 7054d9148442
Successfully built 7054d9148442
```
