### ISSUE TITLE
Accept strings as Cmd parameter when creating a container

### ISSUE THREAD

**Issue by ArmandGrillet** [swipely/docker-api#285]
We can read in the Docker Remote API doc than we can specify a command when creating a container "through a  `Cmd` parameter as a string or an array of strings" ([source](https://docs.docker.com/reference/api/docker_remote_api_v1.18/#create-a-container)). However docker-api seems to only accept array of strings, here is an example.

This code works:
```ruby
Docker::Container.create('Image' => "ubuntu:latest", 'Cmd' => ["sh", "-c", "while true; do echo hello world; sleep 1; done"]).start
```

This code returns  `json: cannot unmarshal string into Go value of type []string`:
```ruby
Docker::Container.create('Image' => "ubuntu:latest", 'Cmd' => "sh -c 'while true; do echo hello world; sleep 1; done'").start
```

**Comment by tlunter** [comment]
That error that comes back is actually from the docker daemon.  I have a suspicion that their docs aren't accurate anymore.  Is there a reason you're trying to use only a string instead of an array? What happens when you supply the string wrapped in an array?

**Comment by ArmandGrillet** [comment]
I'm trying to use a string instead of an array because I'm using a form to create a new container and there is an input where the user can write the commands wanted.

The command used when supplying the string wrapped in an array:
```ruby
Docker::Container.create('Image' => "ubuntu:latest", 'Cmd' => ["sh -c 'while true; do echo hello world; sleep 1; done'"]).start
```
The error message (displayed when inspecting the container):
`"Error": "[8] System error: exec: \"sh -c while true; do echo hello world; sleep 1; done\": executable file not found in $PATH"`
The weird thing is that it looks like docker-py is able to use a string as a command, at least in the documentation:
```python
>>> from docker import Client
>>> cli = Client(base_url='tcp://127.0.0.1:2375')
>>> container = cli.create_container(image='busybox:latest', command='/bin/sleep 30')
>>> print(container)
{'Id': '8a61192da2b3bb2d922875585e29b74ec0dc4e0117fcbf84c962204e97564cd7',
 'Warnings': None}
```

**Comment by tlunter** [comment]
https://github.com/docker/docker-py/blob/master/docker/utils/utils.py#L492 `docker-py` is just taking the string and using a shell-aware split.

```
Python 2.7.8 (default, Aug  6 2014, 13:39:41)
[GCC 4.2.1 Compatible Apple LLVM 5.1 (clang-503.0.40)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import shlex
>>> shlex.split("/bin/sleep 30")
['/bin/sleep', '30']
```

You can do the same in Ruby with:

```
illyrio∴ irb
irb(main):001:0> require 'shellwords'
=> true
irb(main):002:0> "/bin/sleep 30".shellsplit
=> ["/bin/sleep", "30"]
```

**Comment by ArmandGrillet** [comment]
So it's an issue concerning the Docker Remote API and not docker-api, again! Sorry to bother you for nothing @tlunter.
