### ISSUE TITLE
Attaching before starting throws TimeoutError

### ISSUE THREAD

**Issue by pbrisbin** [swipely/docker-api#287]
```rb
require "docker"

container = Docker::Container.create(
  "Image" => "alpine:latest",
  "Cmd" => ["echo", "foo"]
)

container.attach { |s,o| puts "#{s}: #{o}" }
container.start
```

Produces the following:

```
`/home/patrick/.gem/ruby/2.2.2/gems/docker-api-1.21.4/lib/docker/connection.rb:52:in `rescue in request': read timeout reached (Docker::Error::TimeoutError)
        from /home/patrick/.gem/ruby/2.2.2/gems/docker-api-1.21.4/lib/docker/connection.rb:38:in `request'
        from /home/patrick/.gem/ruby/2.2.2/gems/docker-api-1.21.4/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
        from /home/patrick/.gem/ruby/2.2.2/gems/docker-api-1.21.4/lib/docker/container.rb:103:in `attach'``
```

Switching so `#start` is called before `#attach` works, but introduces a race condition if the engine produces output before the `#attach` is ready. The only way to avoid the race is to `#attach` after `.create` but before `#start`.

AFAICT (my go's not great), this is the order that `docker run` does things ([source][]), which means the docker daemon supports it. If that's true, it's something about the gem causing this issue.

[source]: https://github.com/docker/docker/blob/master/api/client/run.go#L106-192

**Comment by tlunter** [comment]
http://docs.docker.com/reference/api/docker_remote_api_v1.18/#attach-to-a-container this lists the option of `logs`.

```
container.attach(logs: true) { |s, o| puts "#{s}: #{o}" }
```

This is what you want.  They are using channels and a lot of deferring in the client which lets them start the request before starting the container.  We don't have that in ruby, so `logs: true` will get you want you want.

**Comment by pbrisbin** [comment]
Thank you for the response. There still seems to be a race using that approach. Internally, docker would

1. Read and send existing logs
2. Attach and send new messages

If output comes between 1 and 2 it'd be missed.

In our project, we've decided to shell out to `docker run`. If you don't consider it a bug that the gem behaves differently than the go client in this regard, feel free to close this.

**Comment by tlunter** [comment]
Another approach could be to start a new thread and start the attach request there.
