### ISSUE TITLE
uninitialized constant Docker::Image in rspec testcase

### ISSUE THREAD

**Issue by ckaiser79** [swipely/docker-api#288]
Hello,

I installed ruby on a Centos7 x64 box to try docker api inside a rspec test. In my testcase and in below example I got a error <code>uninitialized constant Docker::Image</code>. Is this explainable?

The ruby version I tested against is 2.2.1 or 1.9.3.

My installed gems are:

    gem install docker docker-api

Here my first test:

    # irb
    2.2.1 :001 > require 'docker'
     => true 
    2.2.1 :002 > 
    2.2.1 :003 >   image = Docker::Image.create('fromImage' => 'base')
    NameError: uninitialized constant Docker::Image
	    from (irb):3
    	    from /usr/local/rvm/rubies/ruby-2.2.1/bin/irb:11:in `<main>'
    2.2.1 :004 > 

This example brings it one step further:

    2.2.1 :007 > require 'docker'
     => true
    2.2.1 :008 > require 'docker/error'
     => true 
    2.2.1 :009 > require 'docker/base'
     => true 
    2.2.1 :010 > require 'docker/image'
      => true 
    2.2.1 :011 > image = Docker::Image.create('fromImage' => 'base')
    NoMethodError: undefined method `connection' for Docker:Module
	from /usr/local/rvm/gems/ruby-2.2.1/gems/docker-api-1.21.4/lib/docker/image.rb:105:in `create'
	from (irb):13
	from /usr/local/rvm/rubies/ruby-2.2.1/bin/irb:11:in `<main>'

**Comment by tlunter** [comment]
`gem uninstall docker`. That gem is not part of our gem.  It's messing with your load path and thus making the `require`'s not work.

**Comment by ckaiser79** [comment]
Thanks I will try that.

**Comment by rvu95** [comment]
Hello, i have the same problem right there, unfortunately when i'm uninstalling the gem, i found this error:

```
$ bundle exec rspec                                                                                                                                         
Could not find docker-0.3.1 in any of the sources
Run `bundle install` to install missing gems.
```

**Comment by tlunter** [comment]
@rvu95 Looks like you haven't bundle install'd since removing `docker` from your Gemfile or something.  Make sure only `docker-api` is in your Gemfile then run `bundle install`.
