### ISSUE TITLE
1.7.0 needs :user value in exec creation

### ISSUE THREAD

**Issue by y3ddet** [swipely/docker-api#291]
When creating an exec object, the command needs to have the option to include the :User configuration variable, the default user is now root instead of the USER defined in the Dockerfile

**Comment by tlunter** [comment]
@y3ddet how are you creating the Exec object? By `Docker::Exec.create` or by using `container.exec`?

Looks like we'll need to add user here: https://github.com/swipely/docker-api/blob/master/lib/docker/container.rb#L51-L58, right?  Unfortunately the docker docs don't have this updated, so I could only find the reference in their code.

**Comment by y3ddet** [comment]
@tlunter - that's the correct spot. The 'User' son variable is not called out in the API documentation, you have to look at the [CHANGELOG.md](https://github.com/docker/docker/blob/master/CHANGELOG.md) to see the feature even exists. I've verified this works with the following change to container.rb:

```
  def exec(command, opts = {}, &block)
    # Establish values
    tty = opts.delete(:tty) || false
    detach = opts.delete(:detach) || false
    user = opts.delete(:user)
    stdin = opts.delete(:stdin)
    stdout = opts.delete(:stdout) || !detach
    stderr = opts.delete(:stderr) || !detach

    # Create Exec Instance
    instance = Docker::Exec.create(
      'Container' => self.id,
      'User' => user,
      'AttachStdin' => !!stdin,
      'AttachStdout' => stdout,
      'AttachStderr' => stderr,
      'Tty' => tty,
      'Cmd' => command
    )
```

**Comment by y3ddet** [comment]
Looks like the upstream Docker guys acknowledge that this breaks old scripts and are going to fix the default in 1.7.1 back to the container user. We still need support for this in the docker-api library, but it's less critical if 1.7.1 hotfix arrives soon.

https://github.com/docker/docker/pull/14218

**Comment by y3ddet** [comment]
@tlunter Do you want me to create a pull request for the addition of the User option?

**Comment by tlunter** [comment]
@y3ddet sorry about that, yea that'd be wonderful.  Should be simple enough!

**Comment by y3ddet** [comment]
@tlunter I have created a pull request #299 with the change and example code showing how it works
