### ISSUE TITLE
Docker 1.7 error Excon::Errors::SocketError: Connection refused - connect(2) for 10.x.x.x:2376 (Errno::ECONNREFUSED)

### ISSUE THREAD

**Issue by waynehoover** [swipely/docker-api#292]
When trying to use this gem with Docker 1.7 I get this error:

```Excon::Errors::SocketError: Connection refused - connect(2) for 10.x.x.x:2376 (Errno::ECONNREFUSED)```

Does this gem support 1.7?

**Comment by waynehoover** [comment]
Actually, this looks to be an issue on my side.

**Comment by jayantbh** [comment]
@waynehoover facing the same issue, how'd you fix it?
