### ISSUE TITLE
Add docker compose support

### ISSUE THREAD

**Issue by rgarbin** [swipely/docker-api#300]
Add docker compose support  to create, start, stop,, kill containers with a simple YML.

reference: https://docs.docker.com/compose/

**Comment by tlunter** [comment]
@rgarbin I'm a bit confused.  `docker-compose` is a standalone application that the docker company has been writing to create, start, stop and kill containers with a YAML configuration.  If you'd like to, you can write an application to do that using our ruby API.  We're just a way to interact with the remote API in ruby. `docker-compose` already exists.

**Comment by rgarbin** [comment]
I wrote a compose parse(yml) and created my containers using docker-api to run some tests.  I like use  compose because for me,  is a easy way to test my containers and test your comunication out of my application.

I think is so interesting support no docker compose application, but only file(yml) to create and up containers with docker-api. but can be other project, right?

**Comment by tiagodeoliveira** [comment]
I undertand your point @tlunter, but I think that what @rgarbin is trying to say is that it shloud be really helpful if the API had an entrypoint using a YAML file, like an additional method that parses the compose yaml file and orchestrate the containers creation and startup process.
I personally use that all the time, it much more easy to point a YAML file and API startus up everything to you, but as you said, maybe it's not the intention of your API, you just want to interact with docker API letting the user to orchestrate the logic behind that.

**Comment by tlunter** [comment]
@tiagodeoliveira thanks for the clarification.  @rgarbin can definitely understand the desire for that sort of support, but given that the scope of this project is limited to interaction with the remote API, and less orchestration around docker, I think a separate gem that would utilizes this gem and can parse the docker-compose YAML would be the best path forward.

**Comment by rgarbin** [comment]
Thks guys!
