### ISSUE TITLE
can't find pull command

### ISSUE THREAD

**Issue by SydOps** [swipely/docker-api#305]
How to pull the image with this gem. For example, I'd like to pull the `ubuntu:12.04` image, how can I do with ruby docker-api?

    docker pull ubuntu:12.04

Are there something as `image = Docker::Image.pull(REPOSITORY:TAG)`

**Comment by tlunter** [comment]
`Docker::Image.create('fromImage' => 'ubuntu:12.04')`.  Let me know if this works!

**Comment by SydOps** [comment]
Thanks, @tlunter . I can pull the image now.

**Comment by SydOps** [comment]
re-open for the new pull request.

**Comment by SydOps** [comment]
commits are merged.
