### ISSUE TITLE
Pushing multiple tags to registry

### ISSUE THREAD

**Issue by albertogg** [swipely/docker-api#307]
Hello, I don't know if here is the right place to ask this but here it goes...

I'm seeing that if I tag an image multiple times `image.tag(repo: "albertogg/test", tag: "2.rc1", force: true)`, `image.tag(repo: "albertogg/test", tag: "2", force: true)` and then do `image.push` it will only push the first tag. Am I missing something?

```ruby
image.push
=> #<Docker::Image:0x007ffa7210c0b0
 @connection=
  #<Docker::Connection:0x007ffa70aa0038
   @options=
    {:client_cert=>"/Users/albertogg/.docker/machine/machines/dev/cert.pem",
     :client_key=>"/Users/albertogg/.docker/machine/machines/dev/key.pem",
     :ssl_ca_file=>"/Users/albertogg/.docker/machine/machines/dev/ca.pem",
     :scheme=>"https"},
   @url="tcp://192.168.99.100:2376">,
 @id="365cf79887f9",
 @info=
  {"id"=>"365cf79887f9",
   :headers=>
    {"Content-Type"=>"application/tar",
     "Transfer-Encoding"=>"chunked",
     "X-Registry-Config"=>"eyJjb25maWdzIjp7IiI6eyJ1c2VybmFtZSI6IiIsInBhc3N3b3JkIjoiIiwiZW1haWwiOiIifX19"},
   "RepoTags"=>["albertogg/test:2.rc1", "albertogg/test:2"]}>
```

<img width="834" alt="screen shot 2015-08-26 at 12 25 49 pm" src="https://cloud.githubusercontent.com/assets/451539/9491217/acd5d8e8-4bed-11e5-85f8-06e233bfaa2b.png">

Thanks and sorry for posting a question here.

**Comment by tlunter** [comment]
@albertogg I think that's just the nature of how we implemented push.

One option is to do instead of just `img.push`, to do `img.push(nil, repo_tag: 'albertogg/test:2')`.  Specifying the repo_tag will push the correct one.

**Comment by albertogg** [comment]
yeah, thanks, I also saw that we can do `img.push(nil, tag: "2")`... Another thing is that based on the documentation `image.push` returns "true" if the push was successful, but currently it returns _self_ image object.

**Comment by tlunter** [comment]
@albertogg Interesting. Will make note to update that. Thanks.
