### ISSUE TITLE
The way to tag an image is very confused. 

### ISSUE THREAD

**Issue by SydOps** [swipely/docker-api#309]
For example: 

```
irb(main):017:0> image = Docker::Image.create('fromImage' => 'alpine:3.2')
=> #<Docker::Image:0x007fc0e1da44c8 @id="31f630c65071", @info={"id"=>"31f630c65071", :headers=>{}}, @connection=#<Docker::Connection:0x007fc0e1bad750 @url="tcp://192.168.99.100:2376", @options={"..."}>>

irb(main):019:0> image.id
=> "31f630c65071"
```

So image has the id already. 

Normally if I need create a new tag on that image, I should be not required to provide repository name again, defaultly, it should be the image.id.

But when I try to tag it without `repo`, I got below error. 

```
irb(main):014:0> image.tag('tag' => 'test1', force: true)
Docker::Error::ServerError: Repository name can't be empty
```

So we need a new feature to check if no `repo` provided, image.id will be used as default.

I'd like to do the change, but not sure which files I need work on to add this feature, if you know, let me know.

**Comment by tlunter** [comment]
`lib/docker/image.rb` contains everything you need for tagging.

**Comment by tlunter** [comment]
http://docs.docker.com/reference/api/docker_remote_api_v1.16/ This is the docker remote API. You'll want to use this to understand what must be passed to docker.

**Comment by SydOps** [comment]
thanks, I found the codes at https://github.com/swipely/docker-api/blob/master/lib/docker/image.rb#L41

Let me take a look

**Comment by SydOps** [comment]
Hold the pull request. 

	from /Users/bill/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/docker-api-1.22.4/lib/docker/image.rb:43:in `tag'

Problem is at:

    connection.post(path_for(:tag), opts)

**Comment by SydOps** [comment]
Finally i understand the codes. The `image.id` is just the id, one image id can have several repo:tag, which is reasonable to provide repo and tag name at same time. 

No update required, this issue can be closed.
