### ISSUE TITLE
Support for .dockerignore files in build context.

### ISSUE THREAD

**Issue by wpp** [swipely/docker-api#313]
Hi,

I'm transitioning from the docker cli to this gem and I was wondering wether there is support for
`.dockerignore` files? I have a `.dockerignore` in my build context directory and in my case that makes a difference of 300-400 MB.

https://docs.docker.com/reference/builder/
> To increase the build’s performance, exclude files and directories by adding a .dockerignore file to the context directory.

**Comment by grosser** [comment]
It should also respect .gitignore when there is not .dockerignore

working on a PR now ...

**Comment by grosser** [comment]
nvm ... current behavior seems to be that .gitignore is not supported in docker cli ...
