### ISSUE TITLE
Image#push doesn't appear to work

### ISSUE THREAD

**Issue by aalness** [swipely/docker-api#316]
Almost certainly due to user error so maybe this will be obvious but when I do a push like:

```ruby
    image = Docker::Image.get(image_id)
    image.push(nil, repo_tag: "username/foo:v1")
```

I don't see it end up in my registry. I have to `docker push username/foo` from the command line to see it.

Any idea what I'm doing wrong? Thanks!

**Comment by wpp** [comment]
This might be helpful to debug:

    image.push(nil, repo_tag: "username:/foo:v1") do |chunk|
      puts JSON.parse(chunk)
    end

**Comment by tlunter** [comment]
I agree with @wpp.  Let me know if you gleen anything from that. Perhaps that image hasn't been tagged prior to being pushed

**Comment by aalness** [comment]
Thanks guys.

```
...
{"status"=>"Buffering to Disk", "progressDetail"=>{}, "id"=>"d6627d59a80d"}
{"status"=>"Image push failed", "progressDetail"=>{}, "id"=>"d6627d59a80d"}
{"errorDetail"=>{"message"=>"Error pushing to registry: Authentication is required."}, "error"=>"Error pushing to registry: Authentication is required."}
```

Ah, so it won't automatically use my credentials in `~/.dockercfg`?

**Comment by aalness** [comment]
Actually that isn't surprising...I'll close this. Thanks again!
