### ISSUE TITLE
Link containers after start

### ISSUE THREAD

**Issue by mauricioklein** [swipely/docker-api#326]
Is there a way (or maybe the feature is interesting enough to being incorporated on project) to link containers after they've been started.

Currently, I can do so on container creation, but after the container is started, I can't figure out a way to create this linkage.

Thanks!

**Comment by tlunter** [comment]
@mauricioklein I'm not sure that's something we can help with. We're just a ruby client to the docker daemon itself.  I suggest contacting the folks over at: https://github.com/docker/docker

**Comment by mauricioklein** [comment]
Thanks @tlunter!

I was searching for a way to not to deal with container dependencies. Just start them and link after running.

By the way, I'll write my own dependency handler.

Thanks for the quick reply!

**Comment by tlunter** [comment]
@mauricioklein yep, unfortunately we're limited by the daemons capabilities for when we can link.
