### ISSUE TITLE
Docker Compose processor released

### ISSUE THREAD

**Issue by mauricioklein** [swipely/docker-api#327]
Hello everybody!

As @tlunter said, the purpose of this Docker client is to provide a simple and clean way to interact with Docker server. So, no Compose related functionalities will be added to it.

Said so, I've created a Docker compose parser, which uses @tlunter Docker client under the hood.

You can reach compose project [here](https://github.com/mauricioklein/docker-compose-api).

The project is new, so many features are still missing and some bugs are expected. However, it's being evolved constantly.

Hope this can make your life easier.

Thanks!

*PS: Sorry about opening an issue to promote this project, but I think it can be helpful for everybody and avoid @tlunter for answering annoying compose related questions :laughing:*

**Comment by tlunter** [comment]
@mauricioklein Awesome! Can move this knowledge to the README if people are looking for the same thing! :)

**Comment by mauricioklein** [comment]
That would be great!
Thanks @tlunter o/
