### ISSUE TITLE
Please add support for Docker Network

### ISSUE THREAD

**Issue by fishnix** [swipely/docker-api#332]
Hi!  Thanks for this library.  Please add support for the new docker network feature in 1.9.  Thanks!

http://docs.docker.com/engine/userguide/networking/dockernetworks/

**Comment by tlunter** [comment]
Hi @fishnix,

We haven't had much time to follow up with implementing the latest API changes.  If you get a chance and want to try a hand at implementing, I'd be happy to read the PRs or answer any questions!

**Comment by fishnix** [comment]
Thanks @tlunter - I'll see what I can do :+1:

**Comment by smgt** [comment]
Did a PR, #335 .

**Comment by fishnix** [comment]
Thanks!  This looks merged, so I'll close this.
