### ISSUE TITLE
Issues creating a container. What am I doing wrong here?

### ISSUE THREAD

**Issue by treeder** [swipely/docker-api#336]
I'm just trying to get my local directory to mount, but it doesn't seem to work. Everything looks right, but there's nothing in the directory inside the container.

Here's code:

```
require 'docker'

image = 'iron/ruby'
mounts = []
mounts << {
           'Source' => Dir.pwd,
           'Destination': "/app",
           "Mode": "rw",
         }
coptions = {
  'Image' => image,
  'Cmd' => ['sh', '-c', 'ls -al && pwd'],
  "AttachStdout": true,
  "AttachStderr": true,
  'Mounts' => mounts,
  'WorkingDir' => '/app',
}
puts "container options:"
p coptions
container = Docker::Container.create(coptions)
p container.json
container.tap(&:start).streaming_logs(stdout: true, stderr: true) { |stream, chunk| puts "#{stream}: #{chunk}" }
# container.tap(&:start).attach(:stream => true, :stdin => nil, :stdout => true, :stderr => true) { |stream, chunk| puts "#{stream}: #{chunk}" }
container.delete(:force => true)
```

**Comment by tlunter** [comment]
Hmm, is this with docker 1.9?

When we've done volumes previously, we did this: https://github.com/swipely/dockly/blob/master/lib/dockly/build_cache/docker.rb#L53-L65

There is a possibility docker changed stuff though.

**Comment by falexandrou** [comment]
@treeder In my case i had to add `:follow => true`. Don't know if that helps you too.

`eg. container.tap(&:start).streaming_logs(:follow => true, :stdout => true, :stderr => true) do |stream, chunk|`

**Comment by treeder** [comment]
Hey guys, figured it out.

Turns out I just needed to add the Binds. eg:

```ruby
coptions = {
  'Image' => image,
  'Cmd' => ['sh', '-c', 'pwd && ls -al'],
  "AttachStdout": true,
  "AttachStderr": true,
  'WorkingDir' => '/app',
  "HostConfig" => {
    "Binds": ["#{Dir.pwd}:/app"]
  },
}
```

@falexandrou what does the `:follow=>true` do? It seems I don't get all the logs sometimes, but if I enable that, it seems to be more consistent.

**Comment by falexandrou** [comment]
@treeder woah i should have taken the time to read the question carefully, thought was about logging, sorry about that. Yes, that's the way you use `Binds` as described [here](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.21/#create-a-container). 

missing the `:follow` arg, when i was streaming logs, ended up in random behavior with Docker 1.9.1. I got timeouts all the time and / or empty logs. It's mentioned [here](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.21/#get-container-logs). It's probably something like `tail -f` i guess (feel free to correct me if i'm wrong @tlunter )

**Comment by treeder** [comment]
@falexandrou it does seem to be more consistent with that flag set, thanks. 

All good now.
