### ISSUE TITLE
How to get the prompt first when attaching the stdin of the container?

### ISSUE THREAD

**Issue by onesuper** [swipely/docker-api#337]
The behavior of attaching the stdin of the container looks like this to me:

```
$ ruby shell.rb
            (a blank line)
[root@8ccb678b8dd2 /]# date
Fri Nov 20 01:59:33 UTC 2015
[root@8ccb678b8dd2 /]#
```

The blank line is there because the container is waiting for my input (and I just feed a newline). Is there any way to get the prompt first?

My Ruby code:

```
container = Docker::Container.create(
  "Cmd"       => ["bash"],
  "Image"     => "centos:6",
  "OpenStdin" => true,
  "StdinOnce" => true,
  "Tty"       => true
)

container.start()

require "io/console"
STDIN.raw do |stdin|
  container.attach(stdin: stdin, tty: true) do |chunk|
    print chunk
  end
end
```

**Comment by hekaldama** [comment]
I executed your code and I did not receive a blank line. I am using docker version 1.12.0. Are you still getting this with the latest gem version and latest docker?
