### ISSUE TITLE
Can Container.copy do the reverse?

### ISSUE THREAD

**Issue by onesuper** [swipely/docker-api#338]
Docker's API Endpoint has supported this feature:

~~~PUT /containers/(id)/copy?srcPath=/local/path&dstPath=/container/path~~~`

~~~see: https://github.com/docker/docker/issues/5846~~~

Actually, it is the archive api which copies tar ball between host and container

**Comment by Gargron** [comment]
I too am waiting for https://github.com/swipely/docker-api/pull/341 to be merged in

**Comment by tlunter** [comment]
@Gargron @onesuper merged it in v1.25.0

**Comment by TomHutter** [comment]
Could you please update this in the README.md too

**Comment by jayantbh** [comment]
+1 to implement what docker cp does. To copy from host to container.
