### ISSUE TITLE
400 bad request when using in docker 1.9.1

### ISSUE THREAD

**Issue by hanks** [swipely/docker-api#342]
I found here from [synapse](https://github.com/airbnb/synapse/blob/master/lib/synapse/service_watcher/docker.rb#L67),  code below would always throw log out error polling message and `400 bad request` info, does this mean client api version is not compatible with docker daemon version? Thanks

``` ruby
Docker.url = "http://#{server['host']}:#{server['port'] || 4243}"
begin
    cnts = Docker::Util.parse_json(Docker.connection.get('/containers/json', {}))
rescue => e
    log.warn "synapse: error polling docker host #{Docker.url}: #{e.inspect}"
    next []
end
```

**Comment by tlunter** [comment]
I'll need to take a look but i think the API version we're specifying is getting dropped. I will check the API docs today

**Comment by maran** [comment]
Ran into this as well today. @tlunter did you got any time to look into the API and whether it was indeed being dropped?

**Comment by tlunter** [comment]
So, I believe only the push endpoint is getting disabled, versus the whole API version.  Can either of you run with EXCON_DEBUG=true on and see what the request looks like?  There's really no reason a GET request should return `400 Bad Request`.

**Comment by maran** [comment]
I have no idea what EXCON_DEBUG is but I will make some time during my workday tomorrow to try it out on a dev server.

**Comment by tlunter** [comment]
@maran excon is the underlying http client.  It'll print out all the requests and responses it's making very verbosely.

**Comment by maran** [comment]
Thanks that helped! 

```
excon.error.response
  :body          => "client version 1.10 is too old. Minimum supported API version is 1.21, please upgrade your client to a newer version\n"
  :headers       => {
    "Content-Length" => "117"
    "Content-Type"   => "text/plain; charset=utf-8"
    "Date"           => "Tue, 08 Dec 2015 10:11:50 GMT"
  }
```

I found the [API documentation here](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.21/) but I have no idea if these are breaking changes over the API you currently implemented.

**Comment by tlunter** [comment]
@maran the problem here is you're running a really old version of the docker-api gem.  You're going to need to update.
