### ISSUE TITLE
Support using docker tls on heroku

### ISSUE THREAD

**Issue by bfosberry** [swipely/docker-api#343]
I need to be able to connect to my docker api from a heroku app, which requires configuration via env. As such I need to be able to initialize the docker options with the raw values, not file paths. Is there a way to do this now?

**Comment by tlunter** [comment]
Can you not use a relative path to your code that you push to heroku? How does heroku handle assets?

**Comment by someara** [comment]
You can specify opt in the Docker::Connection manually instead of picking them up from the ENV

https://github.com/chef-cookbooks/docker/blob/e6488b80fd27e256022be38d14a513af08dd54f0/libraries/helpers_base.rb#L48-L62

**Comment by bfosberry** [comment]
It's not that I technically can't load from file on heroku, its that I want to dynamically connect to clusters and not commit any keys to my repo

**Comment by tlunter** [comment]
Looking at our underlying HTTP gem, I think you'd want to use something like `cert_store`, `certificate` and `private_key`? I've never messed around with these as opposed to file paths, so I'm not positive on what would work.  Specifically, I'm looking [here](https://github.com/excon/excon/blob/master/lib/excon/ssl_socket.rb#L39-L41) and [here](https://github.com/excon/excon/blob/master/lib/excon/ssl_socket.rb#L79-L86).

https://github.com/excon/excon/blob/master/lib/excon/ssl_socket.rb

As someone had commented here previously, you can create your own `Docker::Connection` object, passing it a set of options and a base URL for the docker server, and pass that to all the top level methods as the last argument.

**Comment by bfosberry** [comment]
I'll give that a go, if not I'll make a PR adding support. Thanks!

**Comment by bfosberry** [comment]
Really the simple solution would be to write ssl keys to disk, and then use tmpfile ...hmm..

**Comment by bfosberry** [comment]
http://stackoverflow.com/questions/6661395/creating-temporary-files-in-heroku yeah, that should work, I'll give that a go, thanks!

**Comment by seanfcarroll** [comment]
@bfosberry did you solve this? If you have time, could you outline how?

**Comment by bfosberry** [comment]
Hey Sean, yeah I basically wrote those files to the filesystem: https://github.com/beanieboi/docker-than-light/blob/018489fa74e28546ec80ec62e0fc80434f303135/config/initializers/docker.rb

**Comment by seanfcarroll** [comment]
Thanks a lot, I appreciate it. Looks like quite an interesting repo!

**Comment by hekaldama** [comment]
@bfosberry fwiw, I used [memfs](https://github.com/simonc/memfs) in my program to do this. It may be helpful for this case as well. 

I opened https://github.com/excon/excon/issues/597 and I am currently attempting a PR to allow this.

**Comment by renemeye** [comment]
Hey,
I was able to solve that by directly loading from ENV Variables in initializer. 

```
Docker.url = ENV["DOCKER_URL"]

if ENV["DOCKER_CERT"] and ENV["DOCKER_KEY"] and ENV["DOCKER_CA"]
  cert_store = OpenSSL::X509::Store.new
  certificate = OpenSSL::X509::Certificate.new ENV["DOCKER_CA"]
  cert_store.add_cert certificate

  Docker.options = {
    client_cert_data: ENV["DOCKER_CERT"],
    client_key_data: ENV["DOCKER_KEY"],
    ssl_cert_store: cert_store,
    scheme: 'https'
  }
end
```

The ENV Variables have to be set with `\n` als line delimiter. Heroku does this automatically. For Local Development I recommend a `.env` File like this:
```
DOCKER_URL='tcp://your.url:2376'
DOCKER_KEY="-----BEGIN RSA PRIVATE KEY-----\nMULTILINE_KEY_WITH_BACKSLASH_N\n-----END RSA PRIVATE KEY-----"
DOCKER_CERT="-----BEGIN CERTIFICATE-----\ nMULTILINE_KEY_WITH_BACKSLASH_N\n-----END CERTIFICATE-----"
DOCKER_CA="-----BEGIN CERTIFICATE-----\ nMULTILINE_KEY_WITH_BACKSLASH_N\n-----END CERTIFICATE-----"
```
