### ISSUE TITLE
Specify container Mounts

### ISSUE THREAD

**Issue by redr0bin** [swipely/docker-api#344]
Hello,

what is the way of passing host directory into container ?
I've tried this:

Docker::Container.create('Image' => 'test-image', 'Mounts' => [{'Source' => '/tmp', 'Destination' => '/tmp1', 'Mode' => 'rw'}])
But after start I see empty Mounts from docker inspect.

**Comment by tlunter** [comment]
When you start the container, trying using `Binds` like here: https://github.com/swipely/dockly/blob/master/lib/dockly/build_cache/docker.rb#L65

**Comment by redr0bin** [comment]
Thanks a lot! This worked like a charm

**Comment by redr0bin** [comment]
I'm really sorry, but Ports are set the same also ? I don't see any documentation regarding Mounts and Ports

**Comment by tlunter** [comment]
http://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#create-a-container If you look here, I think you need to set

```
"ExposedPorts": { "22/tcp": {} },
```

and then nested under `HostConfig`:

```
"HostConfig: { "PortBindings": { "22/tcp": [{ "HostPort": "11022" }] }}
```

It's a bit hard to grok from docker's API reference.
