### ISSUE TITLE
docker authentication on build_from_dir

### ISSUE THREAD

**Issue by rafarost** [swipely/docker-api#347]
Hey! 
I'm trying to build an image that inherits from another image of a private docker registry.

So, before calling build_from_dir method, i'm calling the authenticate! method. The authenticate! runs well, but when I try to build the image, i'm getting the error below:

docker/util.rb:190:in `extract_id': Couldn't find id: {"stream":"Step 1 : FROM xxx.xxx.net:443/xx/x(Docker::Error::UnexpectedResponseError)
{"status":"Pulling repository Xxx.xxx.net:443/xxx/xxxx"}
{"errorDetail":{"message":"Error: image blah:1.0.3 not found"},"error":"Error: image blah:1.0.3 not found"}

I also tried to push against this same registry, with same credentials, and works well! Only the build is failing (when trying to pull from this registry)

Any ideas?

**Comment by tlunter** [comment]
@rafarost can you try this branch? `fix-x-registry-config`  I think we were constructing the object incorrectly.

**Comment by tlunter** [comment]
@rafarost looks like it's working for me, will get a fix ready

**Comment by rafarost** [comment]
Thanks @tlunter !! Works fine!!
