### ISSUE TITLE
Getting a timeout in build_from_dir plus image naming and tagging

### ISSUE THREAD

**Issue by bennythejudge** [swipely/docker-api#354]
Hi,
I am trying to use your gem and I get timeout errors during the `gem install` that takes place during the `Docker::Image.create_from_dir`.
Reading the code and making a lucky guess (because it's undocumented), I have tried using
```
Docker.options[:read_timeout] = 300
```
which seems to make a difference but still doesn't make the timeouts go away (I am not even sure it has any effect). I still get timeouts although not always.
The following is from my terminal (as is):
```
[...]
Fetching dependency metadata from https://rubygems.org/.
.

Using rake 10.4.2
Installing i18n 0.7.0
Installing json 1.8.3 with native extensions
Installing minitest 5.7.0

▽
#!/usr/bin/ruby
Installing thread_safe 0.3.5
Installing tzinfo 1.2.2
Installing activesupport 4.2.3
Installing builder 3.2.2
Installing erubis 2.7.0
Installing mini_portile 0.6.2
Installing nokogiri 1.6.6.2 with native extensions
/var/lib/gems/1.9.1/gems/docker-api-1.24.1/lib/docker/connection.rb:52:in `rescue in request': read timeout reached (Docker::Error::TimeoutError)
	from /var/lib/gems/1.9.1/gems/docker-api-1.24.1/lib/docker/connection.rb:38:in `request'
	from /var/lib/gems/1.9.1/gems/docker-api-1.24.1/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
	from /var/lib/gems/1.9.1/gems/docker-api-1.24.1/lib/docker/image.rb:231:in `build_from_tar'
	from /var/lib/gems/1.9.1/gems/docker-api-1.24.1/lib/docker/image.rb:250:in `build_from_dir'
	from /opt/jenkins-build-library/ruby/jenkins-build.rb:16:in `<main>'
root@i-d734e37b:/opt/jenkins-build-library/ruby# vi jenkins-build.rb
root@i-d734e37b:/opt/jenkins-build-library/ruby# vi jenkins-build.rb
[...]
```

I am also not sure how to tag an image created with `Docker::Image.create_from_dir`.
I am trying:
```
image = Docker::Image.create_from_dir('.')
image.tag(....)
```
Is this the correct behaviour?
Thanks

**Comment by tlunter** [comment]
Is it possible the image build is taking longer than 5 minutes? That's what the `read_timeout` is referring to.  Perhaps set that higher if you're building larger images.

Yes, that would be the correct behavior to tag the image after `create_from_dir`.

**Comment by bennythejudge** [comment]
Thanks
