### ISSUE TITLE
flag provided but not defined

### ISSUE THREAD

**Issue by ethicalhack3r** [swipely/docker-api#357]
When I run ```sudo docker -d``` as per the readme on OS X running ```docker-api (1.25.0)``` on Ruby 2.2.3 I get the following error; 

```
flag provided but not defined: -d
See 'docker --help'.
```

What is the correct command to run?

**Comment by ethicalhack3r** [comment]
It looks like ```docker -d``` was deprecated in favour of ```docker daemon``` in Docker version 1.8.0 https://github.com/docker/docker/blob/master/CHANGELOG.md#180-2015-08-11

However, when I run ```docker daemon``` I get this output:

```
$ docker daemon
docker: 'daemon' is not a docker command.
See 'docker --help'.
```

No other mention in the change logs for the keyword ```daemon```

**Comment by tlunter** [comment]
@ethicalhack3r are you running on OSX? the docker daemon cannot run on OSX.  The reason `docker-machine` works correctly is because it is running `docker daemon` or `docker -d` in a VM and then changes where the client is talking to to that VM.

**Comment by ethicalhack3r** [comment]
Yea, that's the correct problem! Thanks for answering.

Not sure if this is worth mentioning in the readme or not.
