### ISSUE TITLE
archive_in does not untar file content, tar archive is owned by root

### ISSUE THREAD

**Issue by rteusner** [swipely/docker-api#359]
In addition to the issue I opened at the docker github, I kindly ask for help concerning the docker-api gem problem I currently face:

The [archive_in](https://github.com/swipely/docker-api/blob/master/lib/docker/container.rb) function (line 250ff) does not seem to untar my archive within the docker container.
As it is owned by root, I can't untar it later.

Probably I missed some option which has to be passed to the archive_in function?
Or is the created tar file malformed?

Additional details can be found here: [https://github.com/docker/docker/issues/19545](https://github.com/docker/docker/issues/19545)

Thanks for your help!

**Comment by tlunter** [comment]
@rteusner Ah, with the way we defined `archive_in`, it takes the file name and tars it up, then passes it in, which docker will untar on the other side.  So we've tar'd your tar...

**Comment by tlunter** [comment]
Try doing:
```
File.open("tar_file.tar", "rb") do |file|
  container.archive_in_stream("/path/in/container") { file.read(Excon.defaults[:chunk_size]) }
end
```

**Comment by rteusner** [comment]
@tlunter thanks for your fast response.

Sorry, I seemed to have not stated correctly what I did. I pointed the archive_in function directly to a temp folder, not an archive. My problem is however that it was not un-tar'd automatically and is owned by root afterwards. 

If you are not bothered by the mess in the code while I tried it out, you can have a look [here](https://github.com/openHPI/codeocean/commit/113f7652461668e737cacecd74ea964ae00367e8) (lines 133ff).

Also, I seem to have a problem to delete the files after I don't need them any longer. If this fails, I will probably go back to shared folders again. However, it looked interesting so I wanted (and still want) to give it a shot.

**Comment by rteusner** [comment]
Hi again,

I tried it again for several times, and it was reproducible for me every time.
Could you please have another short look at it?

Here are step by step directions to try it out:

1. Create a folder /my_folder or somewhere else, place a random file in it (for example test.txt).
2. Start up a ruby shell and execute the following:

```
require 'Docker'
#Docker.url = 'tcp://192.168.99.100:2376' #if needed, I have my docker daemon running in a vm
container = Docker::Container.create({"OpenStdin"=>true, "StdinOnce"=>true, "AttachStdout"=>true, "AttachStdin"=>true, "AttachStderr"=>true, "Tty"=>true, "Image" => "ubuntu"})
container.start()
container.archive_in('/my_folder/', '/home/my_user', overwrite: false) # just use /home here if no user exists.
```

3. Attach to the created container and have a look what is in the target path /home/my_user

I always got a file (owned by root) with the name of my folder, which is tar archive without any filename extension. 

When pushing a tar file manually through the remote API (for example with the Chrome App Postman), the tar gets unarchived automatically.

I did not use a tar archive as source in my tries with the rails gem, just a folder as described above.

Therefore I believe either I still do something wrong here (and am grateful for a hint), or this is simply a bug. 
 
![bildschirmfoto 2016-02-18 um 17 40 51](https://cloud.githubusercontent.com/assets/3008882/13150639/e13245b4-d666-11e5-8a47-63ff119504c7.png)

![bildschirmfoto 2016-02-18 um 17 39 12](https://cloud.githubusercontent.com/assets/3008882/13150617/ce07c4a0-d666-11e5-8b08-97211dabaad0.png)

**Comment by achamo** [comment]
Hello,

Two years after you, I'm facing the same issue.
My code is as simple as the one written above 
`container.archive_in('source/', '/destination')`

I tried to upload the file I found in /destination with cURL and it works perfectly

`curl -XPUT --upload source-tar -H 'Content-Type: application/x-tar' '127.0.0.1:2375/containers/6aa4351aa3b8aa604d7a938c4db29668adc4776e85aeb10df8b07d40d1865d14/archive?path=/destination&noOverwriteDirNonDir=0'`

**Comment by achamo** [comment]
I think this issue is related to [this piece of code](https://github.com/swipely/docker-api/blob/master/lib/docker/util.rb#L212).
If the path given is a directory it will create a tarball and add this tarball to the list of files to transfer and not the directory itself.
At the end the archive_in method transfers one tarball containing an other tarball. The first tarball is extracting in the output_path leaving a tarball unarchived.

My workaround, almost what @tlunter suggested before 
```
tarball = Docker::Util.create_dir_tar(path)
container.archive_in_stream('/destination', overwrite: true) { tarball.read(Excon.defaults[:chunk_size]).to_s }
```
