### ISSUE TITLE
Wrong parameter serialization while using hash as query parameter

### ISSUE THREAD

**Issue by AlbinOS** [swipely/docker-api#361]
I have an issue when issuing the Docker::Container.all function with the JSON encoded parameters _filters_. 

Calling with _filters: { status: [ "created" ] })_ : 

```
Docker::Container.all(all: 1, filters: { status: [ "created" ] })

Docker::Error::ServerError: invalid character ':' looking for beginning of object key string
Encoded url : /v1.21/containers/json?all=1&filters=%7B%3Astatus%3D%3E%5B%22created%22%5D%7D 
Decoded url : /v1.21/containers/json?all=1&filters={:status=>["created"]}  
```
with _filters: { "status" => [ "created" ] })_ :

```
Docker::Container.all(all: 1, filters: { "status" => [ "created" ] })

Docker::Error::ServerError: invalid character '=' after object key
Encoded url : /v1.21/containers/json?all=1&filters=%7B%22status%22%3D%3E%5B%22created%22%5D%7D
Decoded url : /v1.21/containers/json?all=1&filters={"status"=>["created"]} 
```

The problem is during the serialization of this hash parameter as Excon simply translate via the to_s method and Docker is waiting for a JSON encoded value. The wanted url by docker is something like :

`/v1.21/containers/json?all=1&filters={"status":["created"]}`

Is it a good idea to add an automatic to_json call method on query parameters needed to be JSON encoded before making the call to the docker api ? If you think so, I'll try something and submit a pull request with it.

Thanks and regards,
Albin.

**Comment by AlbinOS** [comment]
After some thoughts, maybe it is better to do it in the call like below : 

`Docker::Container.all(all: 1, filters: { status: [ "created" ] }.to_json)`

It works and its more explicit than anything I could find within the api. And it follow more the API definition that require a JSON encoded value in an explicit way.

What do you think ?

Thanks,
Albin.

**Comment by tlunter** [comment]
Calling `#to_json` is how we've used it previously.  Changing this now would be pretty backwards incompatible.  Sorry for the lack of clarity there. Might be best to include this in a README if you could make a good example.

**Comment by AlbinOS** [comment]
Thanks for your response, I'll write an example and submit it, it's a good idea.

**Comment by AlbinOS** [comment]
Just keeping it alive for my future PR, sorry for the mistake.
