### ISSUE TITLE
Migrate to 1.21 version of the docker remote API

### ISSUE THREAD

**Issue by AlbinOS** [swipely/docker-api#362]
As I have the intention to use docker and this gem heavily, I would like to use the latest version of the docker api.

Is someone already migrating this gem to be compatible with the latest docker API version ? If not, I volunteer to do it. I read your TESTING.md but of course, any other guidelines on a good way to do it are welcome.

Thanks a lot,
Albin.

**Comment by tlunter** [comment]
@AlbinOS is there something missing that you need? The docker API is incredibly loose, so it should just work.  I've considered just removing that from the URL since docker doesn't seem to care about it.

**Comment by AlbinOS** [comment]
@tlunter, I would not say that I really miss something, it's more to be certain to be up to date with the docker API. Especially as I'm starting a new project right now, I would like to be as up to date as possible.

What I understood is that using 1.16 instead of 1.21 when calling the API may change the behavior. For example, when I read on the 1.21 docker remote api changelog page : 

> GET /info now lists engine version information

If we use /1.16/info instead of /1.21/info or /info (as it points to the latest version of the api to my understanding), we would receive different information right ?

For the moment, as you said, I have changed the version to 1.21 in my local gem and everything is working so far. I didn't run the test but I will do it to see if something breaks.

**Comment by tlunter** [comment]
Usually, no, you wouldn't receive anything different.  Very rarely do they actually disable something if you're accessing with an old version which is why we haven't changed it since 1.16.

**Comment by AlbinOS** [comment]
So, If I understand correctly, accessing 1.16 is the same as accessing 1.21 only with the guarantee that the changes made since 1.16 will not break anything ?

Let's assume that they change something on /info so much that any call made before would brake, they will then remove it from the /1.16/ route instead of leaving the older version accessible there ?

Sorry for the trivial question but I'm new with api design, thanks for you time.

**Comment by tlunter** [comment]
@AlbinOS it's better to think that there is only 1 API, and that the version is just another signal should they want to special case something.  More often than not, anything they add will ignore the version number, so it shouldn't be an issue.  There hasn't been that much changing in the API since the beginning, you'll note that docker v1.3 clients actually work fine with docker v1.9.  In the event that they do make a change like that we'll want to bump the version, but using remote API v1.16 is good for now!

**Comment by AlbinOS** [comment]
@tlunter, thanks for the explanation, I'll be more confident using the gem and the api now.
