### ISSUE TITLE
Support docker build -f

### ISSUE THREAD

**Issue by julianfernandez** [swipely/docker-api#375]
In my projects I have several Dockerfiles for only one image in order to create images from diferents OS, so i don`t have  a Dockerfile file, I have Dockerfile.Centos, Dockerfile.debian, Dockerfile.rhel...

I would need docker-api support "docker build --filename". Maybe this new feature could be included in Image.build_from_dir or in a new function Image.build_from_file. 

If you believe that this new feature is interesting I have no problems in making a pull request. If you think that it is better to you implement it, I have no problems

**Comment by tlunter** [comment]
@julianfernandez Can you try `Docker::Image.build_from_dir('/path/to/dir', { 'dockerfile' => 'Dockerfile.Centos' })`? This should work.

**Comment by julianfernandez** [comment]
Perfect, it works. Many thanks @tlunter

**Comment by luiscoms** [comment]
I suggest to put it in the README

**Comment by tlunter** [comment]
Added in https://github.com/swipely/docker-api/commit/61a4497a3af94d199b4c679aa13e56361acf1851
