### ISSUE TITLE
Docker 1.10.2: HTTP communication with daemon fails for UNIX sockets

### ISSUE THREAD

**Issue by Papierkorb** [swipely/docker-api#381]
Hello,

Today I noticed that after updating my system to Docker 1.10.2 I wasn't able to use `docker-api` anymore. The daemon always responded with `400 Bad Requests`.

After some digging I found that `excon` does not handle requests over UNIX sockets per specification.

Just opening this issue to let you know: https://github.com/excon/excon/issues/547

Thanks!

**Comment by tlunter** [comment]
@Papierkorb thanks for noticing that.  I'm sure we can get Excon updated quickly and will make note of the update in the README when it's released.

**Comment by AlbinOS** [comment]
I saw that [excon/excon#548](https://github.com/excon/excon/pull/548) fix this issue. If I use docker-api gem via github link, does I need a version bump or just to run `bundle update` ?

**Comment by tlunter** [comment]
@AlbinOS we need https://github.com/excon/excon to be released.  Once that's done, you can run `bundle update --source excon` to upgrade just excon and it'll fix the issue.

**Comment by AlbinOS** [comment]
@tlunter, thanks, forgot to check if excon was released or not...

**Comment by srust** [comment]
Ok this should probably be closed. I confirmed the API works again with excon >= 0.46.

**Comment by tlunter** [comment]
https://github.com/swipely/docker-api/commit/61a4497a3af94d199b4c679aa13e56361acf1851 Added to README
