### ISSUE TITLE
Streaming logs for run

### ISSUE THREAD

**Issue by nicholasjackson** [swipely/docker-api#383]
Hi,

I'm trying to get the below example to work:

container = Docker::Container.create('Image' => 'busybox', 'Cmd' => ['find / -name *'])
container.tap(&:start).attach { |stream, chunk| puts "#{stream}: #{chunk}" }

The code locks up for a while then I get the following error:
Docker::Error::TimeoutError: read timeout reached

I am guessing that docker run process is completing before attach hooks up to the logs, I am running on a Mac with boot2docker.  In the past the only way I could get the logs was to use the exec command however I am trying to make my build gem compatible with circleci and their docker environment can not use exec so I am switching things back to run.

Is this a problem anyone else has found on mac?

Kind regards,

Nic

**Comment by tlunter** [comment]
Hi @nicholasjackson, I've had better luck doing it this way:

```
container = Docker::Container.create('Image' => 'busybox', 'Cmd' => ['find / -name *'])
thread = Thread.new { container.attach { |stream, chunk| puts "#{stream}: #{chunk}" } }
container.start
thread.join
```

Not the prettiest, but lets the attach method run while start actually gets called later.

**Comment by nicholasjackson** [comment]
Sweet thank you.

It does seem to be an issue with the container finishing before attaching to logs, I will close this issue and might try to add some code to the attach method to double check the container is running.
