### ISSUE TITLE
Question: is there a way to communicate with Docker 1.10+?

### ISSUE THREAD

**Issue by vadviktor** [swipely/docker-api#389]
Hello,

I use some features of Docker 1.10 and I have just run into issues that I wanted to use build parameters introduced in API v1.21.

My question would be, is there a way to use this gem as a multi version one, with falling back to older version API levels when needed?
Is there any use for me to hack on the gem and add new API features via PRs, or should I simply do my fork and be gone? :)

I desperately need this fine project for my current project and I am willing to invest in giving back, if there could be an agreement.

Thanks!

**Comment by tlunter** [comment]
@vadviktor We definitely appreciate adding new features. When we run the test suite we'll limit which versions new features are tested against.

We specify an old API version number, but docker doesn't seem to care about the version number for anything other than keeping the their CLI and daemon versions in sync.  That should make it easy enough to use it against multiple daemons at the same time.

**Comment by vadviktor** [comment]
Hey @tlunter , so basically I should hack on the gem, add the feature I am missing and we will discuss the pull request I may have, is that it? :)

**Comment by tlunter** [comment]
Yep!
