### ISSUE TITLE
Fail to get a command output on my tty

### ISSUE THREAD

**Issue by waghanza** [swipely/docker-api#398]
Hi,

I have created a `docker` image

~~~ruby
image = Docker::Image.create("fromImage" => "debian:jessie")
image.run("apt-get -y update").tag("repo" => "debby")
~~~

After successfully create a container, and attach the output to the current `tty`

~~~ruby
container = Docker::Container.create('Image' => "debby")
container.tap(&:start).attach(:tty => true)
~~~

I want to run a cmmand (in my case it's **autoconf**) with

~~~ruby
container.exec("autoconf")
~~~

but I have

~~~ruby
/var/lib/gems/2.1.0/gems/docker-api-1.28.0/lib/docker/connection.rb:50:in `rescue in request': json: cannot unmarshal string into Go value of type []string (Docker::Error::ServerError)
~~~

does anyone succeed running a command on the current `tty` ?

Regards,

**Comment by tlunter** [comment]
That looks like an error with your command.  Try specifying: `image.run(["apt-get","-y","update"]).tag("repo" => "debby")`.

**Comment by waghanza** [comment]
the error was not with `apt-get -y update` **command**

'till has this `issue`

**Comment by tlunter** [comment]
The error you're seeing is from docker saying that whatever command you've supplied is not valid.  It is saying you're giving the API a string and it wants a list of string.  I suggest looking at all places that you specify either a `run` or a `Cmd` when using docker-api to resolve the issue.

**Comment by waghanza** [comment]
got it, thanks for support
