### ISSUE TITLE
Targeting a precise directory

### ISSUE THREAD

**Issue by waghanza** [swipely/docker-api#399]
Hi,

I have to run a bunch of command inside a running **container**.

However, those `commands` need to bun run in a precise directory.

Is there an equivalent of `WORKDIR` ?

Regards,

**Comment by tlunter** [comment]
@waghanza Do you mean you'll be `exec`ing into a container, or will you spawning a new container for each command and committing to images between each.

**Comment by waghanza** [comment]
@tlunter I mean `exec` on a **container** but with a directory (folder upload in this **container**)

**Comment by tlunter** [comment]
@waghanza It seems `exec` is very underpowered, so you'll have to prepend something like `['cd','DIR','&&']` to the start of your command to emulate that behavior.

**Comment by waghanza** [comment]
@tlunter It' seem that I have trouble doing this
~~~
stdout: rpc error: code = 2 desc = "oci runtime error: exec failed: exec: \"cd\": executable file not found in $PATH"
~~~

**Comment by tlunter** [comment]
Because of the way the args are ran in the container, i think the format should actually be:

```
["/bin/sh","-c","cd #{path} && #{other_command}"]
```

If your other command is currently in an array, you'll want to join it into a single string.

**Comment by waghanza** [comment]
ok, thanks

it worked, but I have a **docker** timeout

**Comment by tlunter** [comment]
`Docker.options.merge(read_timeout: some_large_number)`

It's currently set to 60 for 60 seconds.  If your commands take >60s, try raising it.

**Comment by waghanza** [comment]
it's about compilation, so I'll make a huge timeout .... :+1:

**Comment by waghanza** [comment]
Even with **100000000** seconds, I have a timeout

**Comment by tlunter** [comment]
Oops. Use: `Docker.options.merge!(read_timeout: 100000000)`  `#merge` doesn't mutate. Apologies!
