### ISSUE TITLE
Docker Mac Beta and docker-api

### ISSUE THREAD

**Issue by fwidtmann** [swipely/docker-api#407]
hi,

is there any chance to get docker-api with docker mac beta running?

**Comment by tlunter** [comment]
@fwidtmann What problems are you having? I don't have it, so I can't say why it would or wouldn't work.  Unless they've changed something significantly, I would think it'd just work.

**Comment by fwidtmann** [comment]
if i call `Docker.version` i get `400 Bad Request: malformed Host header`

**Comment by tlunter** [comment]
https://github.com/excon/excon/pull/548 Can you try updating the version of excon?

**Comment by fwidtmann** [comment]
wow, its working. thanks!
