### ISSUE TITLE
Docker built with Go 1.6 not supported

### ISSUE THREAD

**Issue by Confusion** [swipely/docker-api#415]
The current version of `docker-api` (1.29) is not compatible with e.g. the current `docker.io` (1.10.3) package in Ubuntu 16.04. The result of e.g. a `Docker.info` call is
````
400 Bad Request: malformed Host header
````

From https://github.com/emccode/rexray/issues/317 and https://github.com/NVIDIA/nvidia-docker/issues/83 you can surmise that the problem is that the docker in the package is built using Go 1.6.1 and there have been backwards incompatible changes to the Go http package. 

Specifically, they are now checking the validity of the the Host header (related issue: https://github.com/golang/go/issues/13624, from there you can follow to the commit that made the change). The problem is that docker-api sends `/var/run/docker.sock` as the Host header. This is not valid according to [rfc 7230](https://tools.ietf.org/html/rfc7230). [This excon issue](https://github.com/excon/excon/issues/547) makes the case that the Host header should be empty.

Note that it seems that until now the Host field was effectively ignored by Go, so this change should be completely backwards compatible and especially should not affect compatibility with older versions.

BTW. docker-engine 1.10.3 in the Docker repos is built using Go 1.5.3 and works fine with 1.29

**Comment by tlunter** [comment]
@Confusion https://github.com/swipely/docker-api/commit/61a4497a3af94d199b4c679aa13e56361acf1851

This is noted in the README.  If you update your version of excon, this shouldn't be an issue.  Can you validate?

**Comment by Confusion** [comment]
I can confirm that solves the issue. 

I'm a bit surprised Google didn't turn up the README or referenced earlier issue as hits. Lesson learned: re-read READMEs when running into an issue you are pretty sure must have been encountered by many before you :).
