### ISSUE TITLE
Hash values from `containers/json` override those from `containers/(id)/json`

### ISSUE THREAD

**Issue by fonglh** [swipely/docker-api#416]
From Docker API v1.23 onwards, `containers/json` now returns the state of each container as a string.

Thus the `State` hash obtained from calling `containers/(id)/json` is overridden by the string obtained from calling `containers/json`.

This is because the `refresh!` function in `lib/docker/container.rb` prioritises the values from `containers/json` when the `info` and `other` hashes are merged.

As there's more detail from calling `containers/(id)/json`, would it be better to reverse the hash merge so the values from calling `containers/(id)/json` take priority?

Suggested sample implementation in `lib/docker/container.rb`:

```
def refresh!
    other = Docker::Container.all({all: true}, connection).find { |c|
      c.id.start_with?(self.id) || self.id.start_with?(c.id)
    }

    info.merge!(self.json)
    # other && info.merge!(other.info)
    other && other.info.merge!(info)
    info = other.info
    self
  end
```

If this is okay I'll submit a PR.

**Comment by tlunter** [comment]
@fonglh Are the `State` values actually different?

**Comment by fonglh** [comment]
Yes. `containers/json` returns a string, but `containers/(id)/json` returns a more detailed hash.

Here's the response for `containers/json` with Docker API v1.24.

```
[{"Id":"2065aa94ce7853690cf267f4aa19d960b8609cef9be1b55c776d02ba03bdae7f","Names":["/determined_booth"],"Image":"ubuntu","ImageID":"sha256:12543ced0f6f754223eff4cca67b56cbf9f384456ab9deaa824ba9ff28bcfdd6","Command":"bash","Created":1468313114,"Ports":[],"Labels":{},"State":"running","Status":"Up 22 seconds","HostConfig":{"NetworkMode":"default"},"NetworkSettings":{"Networks":{"bridge":{"IPAMConfig":null,"Links":null,"Aliases":null,"NetworkID":"dfddde6472aac68727b764d95aa8f613075db2b9dc692051c1135340d0532f7a","EndpointID":"d38063360354ead25f2a12aaac0817f0560068f0381141f6ffa5d8a9f5bd44dd","Gateway":"172.17.0.1","IPAddress":"172.17.0.2","IPPrefixLen":16,"IPv6Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"MacAddress":"02:42:ac:11:00:02"}}},"Mounts":[]}]
```
The value of `State` is `"State":"running"`, which is the status of the container.

Here's the return value for `containers/(id)/json`:

```
{"Id":"2065aa94ce7853690cf267f4aa19d960b8609cef9be1b55c776d02ba03bdae7f","Created":"2016-07-12T08:45:14.321854698Z","Path":"bash","Args":[],"State":{"Status":"running","Running":true,"Paused":false,"Restarting":false,"OOMKilled":false,"Dead":false,"Pid":4964,"ExitCode":0,"Error":"","StartedAt":"2016-07-14T01:13:55.297968108Z","FinishedAt":"2016-07-12T09:09:19.380682682Z"}, ...
```

The value of `State` here is a hash `"State":{"Status":"running","Running":true,"Paused":false,"Restarting":false,"OOMKilled":false,"Dead":false,"Pid":4964,"ExitCode":0,"Error":"","StartedAt":"2016-07-14T01:13:55.297968108Z","FinishedAt":"2016-07-12T09:09:19.380682682Z"}`

This affects one of the projects I'm involved in. Coursemology/evaluator-slave#49

**Comment by fonglh** [comment]
Docker says this behaviour is expected. docker/docker#24616
