### ISSUE TITLE
Copy a folder from one container to another

### ISSUE THREAD

**Issue by carlochess** [swipely/docker-api#417]
#Hi, i'm trying to copy a folder from a container (container) to another (ejecutor). I've tried this so far but doesn't work :(
```ruby
str = StringIO.new
str = str.binmode
container.archive_out('/tmp/main.hs') { |chunk| str.puts chunk }

ejecutor.archive_in_stream('/', overwrite: true) { str.read }
```
I know that this is not a library issue, sorry.

**Comment by tlunter** [comment]
@carlochess try using `str.write(chunk)` instead of `.puts`.  `.puts` adds a `\n` to the string, which you don't want.
