### ISSUE TITLE
[Windows only] archive_in fails to upload a binary file

### ISSUE THREAD

**Issue by danielmanesku** [swipely/docker-api#419]
Uploading a binary file to a container from Windows environment does not work. Only about 50-200B of data from the file is read and transferred, which makes it corrupted.

After debugging the library, the problem seems to be in [this line](https://github.com/swipely/docker-api/blob/94992073fce13220a867c5820b8c9d730a757b71/lib/docker/util.rb#L210).
`File.read` works alright on Linux for both text and binary files, but on Windows it works alright for text files while it fails to load the binary file entirely.
After testing it a bit, changing that line to
`file_hash[basename] = File.read(local_path, mode: "rb")` seems to solve the issue for both Linux and Windows, and it works in both cases of text and binary files. 

What do you think about this change? Since the library is not reading the content of the file as text, it should work if the file is treated as binary.

**Comment by tlunter** [comment]
@danielmanesku i'll make the change and get a patch release out now.

**Comment by danielmanesku** [comment]
Such a quick reaction, really appreciate it! Thank you!

**Comment by tlunter** [comment]
Release in v1.29.2! Thanks for reporting this.
