### ISSUE TITLE
Support for Docker >= 1.10 events

### ISSUE THREAD

**Issue by jakolehm** [swipely/docker-api#422]
Docker 1.10 introduced improved events api that has more fileds. Currently Docker::Event does not support these fields and may return "empty" data.

https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#/monitor-docker-s-events

**Comment by tlunter** [comment]
Just merged #397 and released in v1.30.0

**Comment by jakolehm** [comment]
That was fast, thanks!
