### ISSUE TITLE
Pulling from AWS ECR always returns Docker::Error::NotFoundError: No such image: 

### ISSUE THREAD

**Issue by dansteen** [swipely/docker-api#439]
It looks like there is an issue when pulling from AWS ECR (amazons container registry service).   docker-api always returns `Docker::Error::NotFoundError: No such image:`

As an example, given the following code:

```
Docker::Image.create('fromImage' => '<redacted>.dkr.ecr.us-east-1.amazonaws.com/org-api:715926df664cbe4f046099b2c45b84f5d871118a')
```

I get the following result:

```
Docker::Error::NotFoundError: No such image: <redacted>.dkr.ecr.us-east-1.amazonaws.com/org-api:715926df664cbe4f046099b2c45b84f5d871118a

        from /home/dsteen/.gem/ruby/2.3.0/gems/docker-api-1.29.1/lib/docker/connection.rb:46:in `rescue in request'
        from /home/dsteen/.gem/ruby/2.3.0/gems/docker-api-1.29.1/lib/docker/connection.rb:38:in `request'
        from /home/dsteen/.gem/ruby/2.3.0/gems/docker-api-1.29.1/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
        from /home/dsteen/.gem/ruby/2.3.0/gems/docker-api-1.29.1/lib/docker/image.rb:126:in `get'
        from /home/dsteen/.gem/ruby/2.3.0/gems/docker-api-1.29.1/lib/docker/image.rb:121:in `create'
        from (irb):34
        from /usr/bin/irb:11:in `<main>'
```

While, on the same machine doing:

```
 docker pull <redacted>.dkr.ecr.us-east-1.amazonaws.com/org-api:715926df664cbe4f046099b2c45b84f5d871118a
```

Results in a successful pull:

```
715926df664cbe4f046099b2c45b84f5d871118a: Pulling from org-api
420890c9e918: Already exists
a3ed95caeb02: Already exists
a94227ae0aee: Already exists
4c2bb81ca079: Already exists
b3b40697a102: Pull complete
d47a83b57d49: Pull complete
468218c1167a: Pull complete
b280bc996242: Pull complete
ee7103997ed1: Pull complete
7a5954993915: Pull complete
Digest: sha256:<redacted>
Status: Downloaded newer image for <redacted>.dkr.ecr.us-east-1.amazonaws.com/org-api:715926df664cbe4f046099b2c45b84f5d871118a
```

Thanks!

**Comment by hekaldama** [comment]
@dansteen are you logged in from the machine you are doing the `docker pull` from? I have seen `Docker::Error::NotFoundError`s when I am not properly passing creds to the daemon.

Check out:

https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/create-an-image

in the "x-registry-auth" section.

**Comment by vlnrajesh** [comment]
@hekaldama What kind of x-registry-auth you have sent to Docker::Image.create

**Comment by hekaldama** [comment]
@vlnrajesh you trying to get my password ;)!?

From the [docs](https://docs.docker.com/engine/api/v1.24/#create-an-image):
> When using this endpoint to pull an image from the registry, the X-Registry-Auth header can be used to include a base64-encoded AuthConfig object.

so something like:
```bash
curl -H "X-Registry-Auth: $(\
  echo '{"username":"jdoe","password":"secret","email": "jdoe@acme.com"}' | base64 \
);" # URL and anything else...
```

I am dusting off old memories here so I may be wrong. LMK if you have more questions.

**Comment by vlnrajesh** [comment]
No @hekaldama 
I have tried with identitytoken getting 404 image not found 
when I tried with username and password it is throwing no pull access
So I was just checking what was the issue

**Comment by KillianKemps** [comment]
If there are other people who were searching like me, I had the same issue because I thought `docker-api` was using the same credentials as the host machine, but in fact you need to explicitly authenticate to ECR with `docker-api`.

As ECR is giving a token to authenticate and not a username and a password, we need to convert this token to a username and a password.

I found the snippet below from [this article](https://stelligent.com/2017/05/02/docker-lifecycle-automation-and-testing-with-ruby-in-aws/), and it helped me to understand how to authenticate to ECR.

Hope it will help others too!

``` ruby
require 'aws-sdk-core'
require 'base64'
require 'docker'
# AWS SDK ECR Client
ecr_client = Aws::ECR::Client.new
# Your AWS Account ID
aws_account_id = '1234567890'
# Grab your authentication token from AWS ECR
token = ecr_client.get_authorization_token(
 registry_ids: [aws_account_id]
).authorization_data.first
# Remove the https:// to authenticate
ecr_repo_url = token.proxy_endpoint.gsub('https://', '')
# Authorization token is given as username:password, split it out
user_pass_token = Base64.decode64(token.authorization_token).split(':')
# Call the authenticate method with the options
Docker.authenticate!('username' => user_pass_token.first,
                     'password' => user_pass_token.last,
                     'email' => 'none',
                     'serveraddress' => ecr_repo_url)
```
