### ISSUE TITLE
Docker-api equivalent of `exec -it`

### ISSUE THREAD

**Issue by jayantbh** [swipely/docker-api#443]
This is in a way related to my issue #442 where I couldn't exec on a swarm container. Turns out that **exec -it** works on the CLI, maybe it would work here too. Does docker-api already have this? If not, could this be added?

**Comment by hekaldama** [comment]
@jayantbh what do you hope to do in ruby by running an interactive (-i) tty (-t)? Curious on the use case.

**Comment by jayantbh** [comment]
One use case could be for running interpreters. Say I have a ruby websocket server, there I could stream in stdin data while getting stdout data.

**Comment by hekaldama** [comment]
Seems like #337 might be helpful. That gives me access to the docker image from the command line at least. Maybe try and throw that into your websocket example and see if it works?

**Comment by jayantbh** [comment]
Another thing, the reason for which I really opened this issue.

container.exec ends up crashing, as mentioned in the issue tagged above (#442).

If container.exec is close to the docker cli equivalent of `docker exec`, and docker exec seems to fail too on the cli, but works using `docker exec -it <command>`, maybe a container.exec variation for -it would work.

**Comment by tlunter** [comment]
@jayantbh try using `#exec(cmd, tty: true)`.
