### ISSUE TITLE
Is this gem still supported?

### ISSUE THREAD

**Issue by hekaldama** [swipely/docker-api#444]
Hi there.

Seems like communication has dried up, is this gem still supported? Are you looking for more contributors or someone to take it over?

Thanks.

**Comment by hekaldama** [comment]
@bfulton @nahiluhmot @tlunter, would you have a minute to respond to this please?

**Comment by tlunter** [comment]
@hekaldama we still maintain this gem. We've had priority doing work for our business currently. I will respond to all the PRs and issues in time. Thanks.

**Comment by hekaldama** [comment]
@tlunter thanks! I would love to help. LMK.
