### ISSUE TITLE
Adding in non-default options on Docker::Network.create

### ISSUE THREAD

**Issue by davejrt** [swipely/docker-api#450]
When I try to create a network with more than a name I get the following error. How does the method want this formatted so you can assign other properties to your network?

network = Docker::Network.create('test')

Trying to add other options from the api like the following:

network = Docker::Network.create ('test1', 'Driver' => 'overlay', 'EnableIPv6' => 'false')

Result in the below error:

network.rb:6: syntax error, unexpected ',', expecting ')'
...ocker::Network.create ('test1', 'Driver' => 'overlay', 'Enab...
...                               ^
network.rb:6: syntax error, unexpected =>, expecting end-of-input
...rk.create ('test1', 'Driver' => 'overlay', 'EnableIPv6' => '...
...

Would appreciate if anyone can advise how to use this method properly.

**Comment by jnummelin** [comment]
You can use following example:
```
    opts = {
         'Driver': 'weavemesh',
           'IPAM': {
             'Driver': 'kontena-ipam',
             'Config': [
               {
                 'Subnet': '10.81.0.0/16',
                 'IPRange': '10.81.128.0/17'
               }
             ],
             'Options': {
               'network': 'kontena'
             }
           }
         }
         network = Docker::Network.create('kontena', opts)
```
