### ISSUE TITLE
Minor version 1.32 dropped support for Ruby 1.9

### ISSUE THREAD

**Issue by ianbamforth** [swipely/docker-api#452]
This is not a minor change!  Definitely worthy of a major version number.  
https://github.com/swipely/docker-api/releases/tag/v1.32.0

**Comment by tlunter** [comment]
Eh, seriously wish bundler handled this scenario better and didn't blow up. We didn't make any change that necessarily dropped 1.9 support, just would like to not have to maintain running against 1.9.  I've pushed 1.32.1 that removes the required ruby version from the gemspec.
