### ISSUE TITLE
Private Repo causes image not found, but docker login worked?

### ISSUE THREAD

**Issue by jmauerhan** [swipely/docker-api#455]
I have zero ruby/rspec experience aside from trying to write an rspec test for my dockerfile based on a tutorial, so apologies if I leave out some vital info. 
I have a basic rspec test to build my dockerfile and check that nodejs is installed. 

```
# spec/Dockerfile_spec.rb

require "serverspec"
require "docker"

describe "Dockerfile" do
    before(:all) do
        Docker.authenticate!('username' => ENV['DOCKER_USERNAME'], 'password' => ENV['DOCKER_PASSWORD'])
        image = Docker::Image.build_from_dir('.')

        set :os, family: :debian
        set :backend, :docker
        set :docker_image, image.id
    end

    it "installs node" do
        expect(package("nodejs")).to be_installed
    end
end
```

I've also tried logging into docker via docker login before running the rspec test, in my .travis.yml. 

Regardless of which method I use for logging in, the test fails saying the image can't be found:

```
 1) Dockerfile installs node
     Failure/Error: image = Docker::Image.build_from_dir('.')
     Docker::Error::UnexpectedResponseError:
       Couldn't find id: {"stream":"Step 1 : FROM my-private-repo\n"}
       {"status":"Pulling repository docker.io/my-private-repo"}
       {"errorDetail":{"message":"Error: image my-private-repo not found"},"error":"Error: image my-private-repo not found"}
       
     # /home/travis/.rvm/gems/ruby-2.2.5/gems/docker-api-1.32.1/lib/docker/util.rb:202:in `extract_id'
     # /home/travis/.rvm/gems/ruby-2.2.5/gems/docker-api-1.32.1/lib/docker/image.rb:266:in `build_from_tar'
     # /home/travis/.rvm/gems/ruby-2.2.5/gems/docker-api-1.32.1/lib/docker/image.rb:278:in `build_from_dir'
     # ./spec/Dockerfile_spec.rb:10:in `block (2 levels) in <top (required)>'
```

The image does exist, and I can pull and build it, but docker-api can't. What should I try next?

Edit: I tested with a public image, and it does get past this point in the test, so that's how I narrowed it down to the private repo.

**Comment by jmauerhan** [comment]
Update 2: If I manually pull the image in my .travis.yml before running the tests, the tests do pass.

**Comment by ctbeiser** [comment]
I can replicate that pulling an image from a private repo fails with these errors.

**Comment by jmauerhan** [comment]
Thanks @ctbeiser

**Comment by tlunter** [comment]
I haven't had much time to look at this. Can you look at the JSON object we pass down to docker and see if they changed the expected structure of that?

**Comment by ctbeiser** [comment]
Haven't gotten a chance, but https://github.com/docker/docker/issues/15759 looks related.
