### ISSUE TITLE
Copy file form HOST into CONTAINER

### ISSUE THREAD

**Issue by anilgulecha** [swipely/docker-api#459]
The scenario is I'm calling into the cloud to a docker host running containers. I have folders on the host which need to be placed in the container.

This api itself is used on a webserver -- hence archive_in does not work.. the folder itself is on the host and not webserver.

How can I do the equivalent of the cli ```docker cp /host/folder containerid:/container/folder``` run on the host?

**Comment by tlunter** [comment]
@anilgulecha Short of somehow getting the file from the host back to the webserver, I don't have a good recommendation. The docker client is doing the same thing as we are with the API. When we've needed to interact with the host and the docker daemon, we've used NetSSH to connect to the instance.
