### ISSUE TITLE
Authenticate against GitLab's integrated registry

### ISSUE THREAD

**Issue by balasankarc** [swipely/docker-api#475]
Hi,

I am trying to use docker-api to authenticate against GitLab's integrated registry, registry.gitlab.com. The `docker` CLI way of doing that was `docker login registry.gitlab.com`. I tried the following but I am getting the error. 
```ruby
[1] pry(main)> require 'docker'
=> true
[2] pry(main)> ENV['DOCKER_HOST'] = 'registry.gitlab.com'
=> "registry.gitlab.com"
[3] pry(main)> Docker.authenticate!(username: '<my username>', password: '<my password>', email: '<my email>')
Excon::Error::Socket: SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: unknown protocol (OpenSSL::SSL::SSLError) (Excon::Error::Socket)
from /home/balasankarc/work/docker-trial/.bundle/ruby/2.3.0/gems/excon-0.55.0/lib/excon/ssl_socket.rb:116:in `connect_nonblock'
```

Any idea what causes this and how to solve it?

**Comment by balasankarc** [comment]
It seems I was doing it wrong. I needed to pass `serveraddress` to `authenticate!`, not set `DOCKER_HOST`. Will close the issue.

BTW, that seems something worth documenting in your README.

**Comment by tlunter** [comment]
@balasankarc please make the PR
