### ISSUE TITLE
docker push question

### ISSUE THREAD

**Issue by pantocrator27** [swipely/docker-api#476]
I have some code that is trying to push to a private docker registry.  I am testing the use case where I have not authenticated to the docker registry and would expect the following code to throw an error but it does not seem to:
```
image = Docker::Image.create('fromImage' => 'centos:6')
image.tag('repo' => "private.registry/centos", 'tag' => '6-latest')
image.push
```

Any help would be greatly appreciated!

**Comment by tlunter** [comment]
@pantocrator27 try running with the environment flag set: `EXCON_DEBUG=true`. There will be a lot of logs, but you should see the response code from docker. We generally only throw errors for bad response codes from docker.  It's possible the output from `image.push` shows the failure.
