### ISSUE TITLE
Container.top outputs "COMMAND" and "CMD" for keys on mac and linux respectively

### ISSUE THREAD

**Issue by varshavaradarajan** [swipely/docker-api#480]
The output of `container.top` is obtained from `docker top` and the keys(or titles) are different on linux and mac. 

The response of the API could be consistent with respect to this and change the title to be one or the other.

**Comment by tlunter** [comment]
@varshavaradarajan we generally try not to mess with the output from the docker API itself. Probably want to file a bug on docker since this inconsistency is just odd.
