### ISSUE TITLE
Options in Image.build_from_dir

### ISSUE THREAD

**Issue by photosojourn** [swipely/docker-api#482]
I have a use case where I need to set the no-cache option when calling build_from_dir. I have tried passing it as a hash but it just gets ignored and the cached results are used. How can I override the behaviour? It might be worth updating the doc if its unclear.

Thanks in advance!

**Comment by tlunter** [comment]
@photosojourn can you include a code snippet?

**Comment by alboyadjian** [comment]
@photosojourn After reading the api docs for the `/build` endpoint, I got this working by specifying `nocache: true` https://docs.docker.com/engine/api/v1.37/#operation/ImageBuild
