### ISSUE TITLE
Very confusing environment variable issue

### ISSUE THREAD

**Issue by scottrobertson** [swipely/docker-api#486]
I have the following code:

```
container = image.run("sh script.sh", {
  'Env' => [
    "FILE_NAME=thishas17chars123",
    "FILE_NAME_OTHER=thishas18chars123",
    "FILE_NAME_OTHER_OTHER=thishas19chars1234",
  ]
})
```

Inside the script.sh i am simply running `printenv`. Here is the response to that:

```
HOME=/root
"FILE_NAME_OTHER=thishas18chars123
BPATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
)FILE_NAME_OTHER_OTHER=thishas19chars1234
PWD=/
FILE_NAME=thishas17chars123
```

As you can see, any env var with more than 17 chars is prepending random things to the beginning of the env var key, including PATH. 

If i run this with:

```
docker run -e FILE_NAME='thishas17chars123' -e FILE_NAME_OTHER='thishas18chars123' -e FILE_NAME_OTHER_OTHER='thishas19chars1234' image sh script.sh
```

It's fine and i get the following:

```
HOME=/root
FILE_NAME_OTHER=thishas18chars123
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
FILE_NAME_OTHER_OTHER=thishas19chars1234
PWD=/
FILE_NAME=thishas17chars123
``` 

I have tried adding single and double quotes around the env var values, but it's the same result

**Comment by scottrobertson** [comment]
I added:

```
puts opts.to_json
```

Above this line: https://github.com/swipely/docker-api/blob/master/lib/docker/container.rb#L338

And the response is:

```
"Env":["FILE_NAME=thishas17chars123","FILE_NAME_OTHER=thishas18chars123","FILE_NAME_OTHER_OTHER=thishas19chars1234"]
```

So it looks like the issue is potentially with the Docker API and not this library... urgh.

**Comment by scottrobertson** [comment]
The `hash` that comes back even contains the correct keys.

**Comment by scottrobertson** [comment]
I have submitted this to the Docker repo. I will close this now as I am pretty sure the library is not causing the issues. Will reopen if I am proven wrong. https://github.com/moby/moby/issues/33507

**Comment by scottrobertson** [comment]
Opening this again. Based on the fact that doing this via raw curl doesn't cause the same issues, I think it must be something to do with this library, or potentially `excon`

**Comment by tlunter** [comment]
@scottrobertson please run with `EXCON_DEBUG=true` and that should print out the body of the request.

**Comment by tlunter** [comment]
@scottrobertson per the linked issue, it looks like we're all set? I noticed you didn't share how you got those logs, but I suspect it was https://github.com/swipely/docker-api/blob/master/lib/docker/container.rb#L158-L160 and not via https://github.com/swipely/docker-api/blob/master/lib/docker/container.rb#L191-L199 ?
