### ISSUE TITLE
Can't search private image

### ISSUE THREAD

**Issue by pocke** [swipely/docker-api#489]
Problem
=====

If we use private repositories, we can't find the repositories by `Docker::Image.search`.

```ruby
Docker.authenticate!(username: name, password: pass, serveraddress: 'some.addr')
Docker::Image.search('term' => 'my-private-repo') # => []
```

However, we can **pull(create)** the image.

```ruby
Docker.authenticate!(username: name, password: pass, serveraddress: 'some.addr')
Docker::Image.create('fromImage' => 'my-private-repo') # => Docker::Image
```

Because `Docker::Image.create` uses credentials, but `Docker::Image.search` does not use.
https://github.com/swipely/docker-api/blob/0800f8c014f5a895307a9aa0afde98393810b9f2/lib/docker/image.rb#L209
https://github.com/swipely/docker-api/blob/0800f8c014f5a895307a9aa0afde98393810b9f2/lib/docker/image.rb#L110

Workaround
=======

```ruby
credentials = Docker.creds
headers = Docker::Util.build_auth_header(credentials) || {}
conn = Docker.connection
resp = conn.get(
  '/images/search',
  {term: image_name},
  headers: headers
)
Docker::Util.parse_json(resp)
```

We can use the above workaround instead of `search` method. However, I think this method should support credentials.

**Comment by tlunter** [comment]
@pocke can you open a pull request for this?

**Comment by pocke** [comment]
@tlunter opened. #490
