### ISSUE TITLE
any plan to support services/stack api ?

### ISSUE THREAD

**Issue by cmingxu** [swipely/docker-api#492]
I want to know do we have plan to support API for docker swarm mode as well as services/stacks API?

**Comment by tlunter** [comment]
I think this gem adds support for swarm support: https://github.com/mikejmoore/docker-swarm-sdk .  It wraps this gem.

**Comment by wrein** [comment]
I'm starting to use this fantastic gem and I really miss the possibility to interact with stack objects.
