### ISSUE TITLE
How to pass --network=host to Container.start?

### ISSUE THREAD

**Issue by jacek99** [swipely/docker-api#495]
Been trying multiple options, none of them work.
Not clear from documentation.

Thank you

**Comment by tlunter** [comment]
https://docs.docker.com/engine/api/v1.30/#operation/ContainerCreate Check out HostConfig >> NetworkMode.

**Comment by adamdavis40208** [comment]
For other people running into this: the magic is 

>Any other value is taken as a custom network's name to which this container should connect to.

```
container = image.run("command", {
      'HostConfig' => { "NetworkMode" => "project-name_default"}
  })
```
