### ISSUE TITLE
Docker build_from_tar is looking for

### ISSUE THREAD

**Issue by mazzy89** [swipely/docker-api#499]
I'm building the image with the tar file by calling:

`Docker::Image.build_from_tar(File.open('/caches/activemq.tar', 'r'))`

but it raises an exception because it is looking for the Dockerfile.

```
#!/bin/sh -eo pipefail
export DOCKER_URL=$DOCKER_HOST
bundle exec rspec --profile 10 \
                  --format progress
F

Failures:
  1) Dockerfile check that ActiveMQ is installed
     Failure/Error: image = Docker::Image.build_from_tar(File.open('/caches/activemq.tar', 'r'))
     Docker::Error::ServerError:
       Cannot locate specified Dockerfile: Dockerfile
       
     # ./vendor/bundle/ruby/2.4.0/gems/docker-api-1.33.5/lib/docker/connection.rb:50:in `rescue in request'
     # ./vendor/bundle/ruby/2.4.0/gems/docker-api-1.33.5/lib/docker/connection.rb:38:in `request'
     # ./vendor/bundle/ruby/2.4.0/gems/docker-api-1.33.5/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
     # ./vendor/bundle/ruby/2.4.0/gems/docker-api-1.33.5/lib/docker/image.rb:262:in `build_from_tar'
     # ./spec/Dockerfile_spec.rb:7:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Excon::Error::InternalServerError:
     #   Expected([200, 201, 202, 203, 204, 301, 304]) <=> Actual(500 InternalServerError)
     #   ./vendor/bundle/ruby/2.4.0/gems/excon-0.57.0/lib/excon/middlewares/expects.rb:7:in `response_call'

Top 1 slowest examples (0.00002 seconds, 0.0% of total time):
  Dockerfile check that ActiveMQ is installed
    0.00002 seconds ./spec/Dockerfile_spec.rb:20

Finished in 7.74 seconds (files took 0.85275 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/Dockerfile_spec.rb:20 # Dockerfile check that ActiveMQ is installed

Exited with code 1
```

**Comment by tlunter** [comment]
@mazzy89 This method is essentially the same as `build_from_dir`, which is the same as `docker build dir` except that we allow passing your own tar directly versus tarring up a directory.  This is how the docker client itself works.

**Comment by mazzy89** [comment]
Yes in know but this doesn't explain why that error. I have Dockerfile in
the dir so why raising that error?


From: Todd Lunter <notifications@github.com> <notifications@github.com>
Reply: swipely/docker-api
<reply@reply.github.com>
<reply@reply.github.com>
Date: 26 October 2017 at 16:29:26
To: swipely/docker-api <docker-api@noreply.github.com>
<docker-api@noreply.github.com>
CC: Salvatore Mazzarino <dev@mazzarino.cz> <dev@mazzarino.cz>, Mention
<mention@noreply.github.com> <mention@noreply.github.com>
Subject:  Re: [swipely/docker-api] Docker build_from_tar is looking for
(#499)

@mazzy89 <https://github.com/mazzy89> This method is essentially the same

**Comment by tlunter** [comment]
can you run `tar -tf '/caches/activemq.tar'` and verify it's not in a subdirectory below the root of the tar archive?
