### ISSUE TITLE
pass env to docker image in build_from_dir

### ISSUE THREAD

**Issue by futantan** [swipely/docker-api#505]
Is there any way to pass env to docker image when calling `build_from_dir` method? I read the document but not found any solution to do this.

**Comment by tlunter** [comment]
You can't pass an environment, but you can pass buildargs that require an `ARG` instruction within the Dockerfile.

**Comment by bcg62** [comment]
I think this is more for non static ARGs, IE proxies.

`docker build --build-arg http_proxy=$http_proxy --build-arg https_proxy=$http_proxy`

Is there a way to pass these to `build_from_dir` im looking for a way to do the same.

**Comment by nzin-appdirect** [comment]
Hi @bcg62, did you managed to pass build args? We face the same problem

**Comment by shanet** [comment]
Looks like the options are passed all the way down to the POST request without being manipulated at all<sup>[1]</sup>. The Docker docs state that the `buildargs` field should key value pairs in JSON so this should work:

```
Docker::Image.build_from_dir '.', buildargs: {key: value}.to_json
```

[1] https://github.com/swipely/docker-api/blob/c1387816b6a9d88fe0e26a81af0f4bb3533a18a2/lib/docker/connection.rb#L91

**Comment by nzin-appdirect** [comment]
I think we figured out, something like:
```Docker::Image.build_from_dir('.', { 'dockerfile' => './Dockerfile', 'buildargs' => { 'myarg': myvalue } } )```
