### ISSUE TITLE
Did you encounter this issue? 

### ISSUE THREAD

**Issue by amihaiemil** [swipely/docker-api#514]
Hey, 

I am also writing a [docker-java-api](https://www.github.com/amihaiemil/docker-java-api). 

I make an HTTP call over the unix socket, get the 200 OK response with the expected content, but also a second response which is 400 BAD REQUEST with no body. More details [here](https://stackoverflow.com/questions/48569991/docker-api-returns-200-ok-then-400-bad-request).

Did you have this issue? Any hint would be greatly appreciated.

**Comment by tlunter** [comment]
This wasn't something we hit, but we also use another ruby gem for our HTTP requests that made treating Unix socket vs TCP socket simple.

**Comment by amihaiemil** [comment]
@tlunter I see. Thanks, anyway  :)
