### ISSUE TITLE
Container create: AutoRemove has no effect

### ISSUE THREAD

**Issue by kaspernj** [swipely/docker-api#517]
I want the container to be automatically removed once it exits.

According to the API this should be possible by setting HostConfig -> AutoRemove to true: https://docs.docker.com/engine/api/v1.34/#operation/ContainerCreate

I am using this code:
```ruby
container = Docker::Container.create(
  {
    "Image" => container_image,
    "name" => docker_container_name,
    "NetworkMode" => "bridge",
    "HostConfig" => {
      "AutoRemove" => true
    }
  },
  @docker_connection
)
```

I have a small piece of code to ensure that AutoRemove is indeed set:
```ruby
auto_remove = container.info.fetch("HostConfig").fetch("AutoRemove")
raise "The 'AutoRemove' setting should be true but wasnt: '#{auto_remove}'" unless auto_remove
```

This check fails every time.

I am using version 1.34.0 of the gem and version 0.60.0 of Excon.

**Comment by TvL2386** [comment]
I've installed the latest version (docker-api-1.34.2) of the gem.
I also tried the AutoRemove => true. Same issue

```
$ docker version
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:10:45 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:09:19 2017
  OS/Arch:	linux/amd64
  Experimental:	false
```

Code:
```ruby
    container = Docker::Container.create(
      'name' => 'credis',
      'Image' => 'redis',
      'ExposedPorts' => { '6379/tcp' => {} },
      'HostConfig' => {
        'AutoRemove' => true,
        'PortBindings' => {
          '6379/tcp' => [{ 'HostPort' => '6381' }]
        }
      }
    )

    container.start
```

**Comment by TvL2386** [comment]
```
$ docker inspect credis | grep AutoRemove
            "AutoRemove": false,
```

Weird!

**Comment by tlunter** [comment]
Can you see if it works with the head of `release-2.x`?  Try using: 
```
gem 'docker-api', git: 'https://github.com/swipely/docker-api.git', branch: 'release-2.x'
```

**Comment by TvL2386** [comment]
I added your line to my rails Gemfile (group :development) and it works!

**Comment by TvL2386** [comment]
Problem solved! Thank you very much :)

**Comment by TvL2386** [comment]
alrighty... I'm no guru when it comes to this, but this line seems to work:

```
gem 'docker-api', git: 'https://github.com/swipely/docker-api.git', ref: '9eb14c6'
require 'docker'
```

Thanks, I'll just use this for now. I want to simply be able to launch dev containers from a rake task...
Off-topic: I don't want it in rails, so I extracted it to a development.rake file to launch all dev containers.

**Comment by TvL2386** [comment]
removed my previous comment, it was incorrect and a bit off-topic

**Comment by zt2** [comment]
Just patch `Docker::Version` to __1.37__ in your code will solve this problem

```
Docker::API_VERSION = '1.37'
```

**Comment by tlunter** [comment]
@zt2 why would you patch the gem versus just using a version of the gem that's been tested to not break. Please use:

```
gem 'docker-api', git: 'https://github.com/swipely/docker-api.git', branch: 'release-2.x'
```

**Comment by kaspernj** [comment]
I have tested this over the last week on my own CI testing app www.peakflow.io and it works great :-)

I am just about the remove my custom container deletion cleanup code, which will greatly simplify my app :-)

Good job! :-)
