### ISSUE TITLE
Persist `Docker.authenticate!` to `~/.docker/config.json`

### ISSUE THREAD

**Issue by marcelocarlos** [swipely/docker-api#528]
`Docker.authenticate!` works great, but it doesn't persist the authentication metadata to `~/.docker/config.json`. 

That works fine if you authenticate and rely on that authentication on the same script. However, if you have different scripts for different purposes (one for authenticating, a different one for pushing and tagging, etc) the authentication won't persist.

It would be great if the ability of creating/updating `~/.docker/config.json` when invoking `Docker.authenticate!` was supported, even if it is something optional.

To simulate this:

```
$ mv ~/.docker/config.json ~/.docker/config.json.old
$ ./authenticate.rb # script that invokes `Docker.authenticate!`
$ cat  ~/.docker/config.json
No such file or directory

$ docker login ....
$ cat  ~/.docker/config.json
{
	"auths": {
		"<registry-id>.dkr.ecr.<region>.amazonaws.com": {}
	},
	"HttpHeaders": {
		"User-Agent": "Docker-Client/18.03.1-ce (darwin)"
	},
	"credsStore": "osxkeychain"
}
```

**Comment by tlunter** [comment]
@marcelocarlos the gem isn't really meant for working in tandem with the CLI. I'd recommend keeping this sort of global configuration within your scripts if that's a feature you're looking for.
