### ISSUE TITLE
Can't pull from private registry when using .docker/config.json auth file

### ISSUE THREAD

**Issue by wlchn** [swipely/docker-api#532]
There is an auth key for registry.example.com in /home/ubuntu/.docker/config.json.
So that I can use "docker pull" pull image from this registry. 
But when using docker-api, I can't pull any image by execing 'Docker::Image.create', 
eg.
```
Docker::Image.create('fromImage' => 'registry.example.com/helloworld:latest')
```
error: 
```
Traceback (most recent call last):
        1: from (irb):32
Docker::Error::ServerError (Get https://registry.example.com/v2/helloworld/manifests/lasted: denied: access forbidden)
```

**Comment by tlunter** [comment]
@wlchn As far as I know, we've never added anything to this gem that reads from that file.
