### ISSUE TITLE
Error undefined method create for Docker::Image:Class

### ISSUE THREAD

**Issue by BrayanArrieta** [swipely/docker-api#534]
Hello I have an error with some of the methods of the classes Image and Container, I can connect from my application and I configure the docker-api, I test the method `Docker::Image.all` and it work but with the method create doesn't work and raise an exception `undefined method create for Docker::Image:Class`. Thanks for help !!

This it's a part of the code
```
Docker.url = 'tcp://localhost:2375/'
image=Docker::Image.create('fromImage' => 'ubuntu:14.04')
```

**Comment by dpsi** [comment]
Do you have a class or module with the same name as the ones in the gem? (Docker, Image, etc.)

**Comment by BrayanArrieta** [comment]
Not I just import the gem, I don't have any Class with those names

**Comment by BrayanArrieta** [comment]
I'm use rails 3.2.8 it's for work project.

**Comment by BrayanArrieta** [comment]
Thanks for all, I fix the error reboot the computher, the error was because the server nginx with passenger. Thanks for the help !!
