### ISSUE TITLE
Unable to connect to an Artifactory Instance

### ISSUE THREAD

**Issue by APayden** [swipely/docker-api#535]
My team works with an Artifactory instance set up with Docker repositories.  When I try to authenticate:
```
Docker.authenticate!(username: 'username', password: 'password', email: 'email@company.com', serveraddress: 'https://docker.server.net')
```

and pull an image:
```
Docker::Image.create(fromImage: 'repository:image')
```

I get an error message stating:
```
Docker::Error::ServerError (Get https://registry-1.docker.io/v2/repository/manifests/manifests/image: unauthorized: incorrect username or password)
```

Yes, the double manifests is correct.  However, why isn't the call using the serveraddress I set up in authentication?

**Comment by rlgomes** [comment]
@APayden how did you fix this ? seems like you closed it shortly after opening it.
