### ISSUE TITLE
Consider transferrring maintenance of this repository

### ISSUE THREAD

**Issue by tas50** [swipely/docker-api#549]
Hi maintainers. I'm curious if you'd be open to transferring the maintenance of this gem to Chef (https://chef.io). We utilize this gem in our compliance offering Chef InSpec and for systems testing in our Chef Workstation product. It's pretty critical to us and we'd like to see that things are updated to at least a new enough API revision that it will support Docker on Windows. Let me know at tsmith@chef.io.

**Comment by tlunter** [comment]
Hi @tas50 

I had made a branch a little while ago to test this out. It just removed the version argument in the endpoints, and I suspect this'll work for that: https://github.com/swipely/docker-api/tree/release-2.x

It unfortunately does mean there is the possibility of unexpected differences when you use an unversioned endpoint and have hosts with different docker versions between them. I suspect we could add the possibility of setting the version in a global class variable or using a connection level variable to reduce this case.

Would that work for you?

**Comment by zenspider** [comment]
Hi. I'd like to revisit this topic. The project hasn't seen a commit (on master) since January.

The comment above seems to address certain aspects about API changes, but doesn't address the actual topic of this issue, which is the possibility of transferring ownership to chef. What do you think about OP's request? Where does this stand?

**Comment by tlunter** [comment]
@zenspider are there particular challenges you're facing that you're looking to address? I am not particularly keen on transferring ownership to chef at this time. I did follow up on this issue in 8 hours from the initial request and received no follow up.

Also, the initial request included transferring ownership but ultimately pointed out the real pain point. Which I responded to.

**Comment by CapCap** [comment]
@tlunter 20 outstanding pull requests and 60 open issues, last commit was 1.5 years ago: this repository is abandoned. Please let @tas50 and chef take this over: they already have a fork https://github.com/chef/docker-api that is 11 commits ahead. This is a great project, please don't let it die for no reason.

**Comment by tlunter** [comment]
Since I am still not getting feedback on any issue where @tas50 replies, I'm going to close this issue.
