### ISSUE TITLE
Timeout when building multi-stage image using a BIG (4gb) image on CI

### ISSUE THREAD

**Issue by zoispag** [swipely/docker-api#550]
Hi,

I have a failing test build on my CI server, which doesn't happen on my local environment.
The specific test builds an image from from a multi-stage Dockerfile, which gets an image from a private registry. I added the `::Docker.authenticate!()` and the images looks like it get's pulled with no problem. 

```ruby
    ::Docker.options[:read_timeout] = 3000
```

I extended the read_timeout even to a ridiculous number `30000` but it fails after 1 minute and few seconds with the following reason:

```
Command "cat /etc/os-release" confirm debian version
	file:///opt/ExtraAgentOne/work/290360a68beb1190/docker_images/tests/spec/scheduler/dockerfile_spec.rb:29
	[Test Output]
	      confirm debian version (FAILED - 1)
	Docker::Error::TimeoutError: read timeout reached
	Docker::Error::TimeoutError: read timeout reached

	Stack trace:
	/var/lib/gems/2.3.0/gems/docker-api-1.34.2/lib/docker/connection.rb:52:in `rescue in request'
	/var/lib/gems/2.3.0/gems/docker-api-1.34.2/lib/docker/connection.rb:38:in `request'
	/var/lib/gems/2.3.0/gems/docker-api-1.34.2/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
	/var/lib/gems/2.3.0/gems/docker-api-1.34.2/lib/docker/image.rb:274:in `build_from_tar'
	/var/lib/gems/2.3.0/gems/docker-api-1.34.2/lib/docker/image.rb:293:in `build_from_dir'
	./spec/scheduler/dockerfile_spec.rb:18:in `block (2 levels) in <top (required)>'
	------------------
	--- Caused by: ---
	IO::EAGAINWaitReadable:
	  Resource temporarily unavailable - read would block
	  <internal:prelude>:76:in `__read_nonblock'
	[Test Output]
```

My serverspec test which fails is the following:

```ruby
require 'docker'

describe "Dockerfile" do
  before(:all) do
    ::Docker.authenticate!(
      'username' => ENV['REG_USR'],
      'password' => ENV['REG_PWD'],
      'serveraddress' => ENV['REG_URL']
    )

    # Set the timeout to a much higher value. 
    ::Docker.options[:read_timeout] = 3000

    @image = ::Docker::Image.build_from_dir('.', 't' => 'scheduler:rspec')

    set :os, family: :debian
    set :backend, :docker
    set :docker_image, @image.id
  end

  describe command('cat /etc/os-release') do
    it "confirm debian version" do
      expect(subject.stdout).to match(/Debian/)
      expect(subject.stdout).to match(/9 \(stretch\)/)
    end
  end

  # [...]

end
```

If it makes a difference,locally I run the test with `rspec dockerfile_spec.rb` but on my CI server (TeamCity) it uses a Rake runner. From the build logs I see: `RSpec Options: dockerfile_spec.rb --color --format documentation --require teamcity/spec/runner/formatter/teamcity/formatter --format Spec::Runner::Formatter::TeamcityFormatter`

Any idea?

**Comment by tlunter** [comment]
https://github.com/swipely/docker-api/blob/master/lib/docker.rb#L93-L95 It looks like these options are passed to the connection and then memoized. You'll probably see a difference if you swap the order of the authenticate call and the read_timeout assignment.

**Comment by zoispag** [comment]
This actually did the trick! Thanks a lot @tlunter !
