### ISSUE TITLE
Warning: URI.escape is obsolete (Ruby 2.7.0)

### ISSUE THREAD

**Issue by hezanathos** [swipely/docker-api#557]
URI.escape is obsolete in Ruby 2.7.0, so using the gem generates warnings.

```
/usr/local/bundle/gems/docker-api-1.34.2/lib/docker/image.rb:129: warning: URI.escape is obsolete
```

The problematic line is : https://github.com/swipely/docker-api/blob/master/lib/docker/image.rb#L129

**Comment by tas50** [comment]
This fork has the fix for those warnings: https://github.com/chef/docker-api

**Comment by tlunter** [comment]
There was a pull request opened here with regards to this issue here: https://github.com/swipely/docker-api/pull/551#issuecomment-629844221 but notably swapping from `URI.escape` and `URI.encode` to `CGI.escape` doesn't seem to be a solution that works as a drop in (the tests for these cases fail).

**Comment by rmoriz** [comment]
@tlunter As far as I can see the test pass and fail for older Rubies just because of a broken travis setup (bundler version)

**Comment by tlunter** [comment]
Hey folks, can try now with v2.0.0.pre.1. There are some other changes in there that I think many folks would benefit from. Let me know if you see any issues.
