### ISSUE TITLE
warning: URI.escape is obsolete

### ISSUE THREAD

**Issue by dvenrao** [swipely/docker-api#559]
We are seeing below warnings with ruby 2.7.0 and docker-api-1.34.2: 

/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/container.rb:346: warning: URI.escape is obsolete
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/image.rb:129: warning: URI.escape is obsolete
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/container.rb:346: warning: URI.escape is obsolete
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/image.rb:129: warning: URI.escape is obsolete
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/container.rb:346: warning: URI.escape is obsolete
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/image.rb:129: warning: URI.escape is obsolete
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/container.rb:346: warning: URI.escape is obsolete
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/container.rb:346: warning: URI.escape is obsolete
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/container.rb:346: warning: URI.escape is obsolete
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/image.rb:129: warning: URI.escape is obsolete

**Comment by tlunter** [comment]
@dvenrao we've just released docker-api v2 which has minor code removal, and fixes this issue. I'm not sure if @tas50 has forced users of chef over to their fork, but this latest release should resolve those issues.
