### ISSUE TITLE
validate_version! doesn't exist

### ISSUE THREAD

**Issue by AdamBark** [swipely/docker-api#561]
but it is mentioned in the README

**Comment by AndrewLaptev** [comment]
Me too:
![image](https://user-images.githubusercontent.com/38818882/95919957-30924280-0db7-11eb-94ef-4ad86349e7a1.png)

**Comment by phaelyn** [comment]
Hey, this method was actually removed in version 2. Just merged a change so that it's no longer referenced in the README!
