### ISSUE TITLE
Destroy an image by its repository

### ISSUE THREAD

**Issue by Soulou** [swipely/docker-api#80]
```ruby
puts image.info["Repository"] image.info["Tag"]
# repo1/app latest
image.tag repo: "repo2/app"
image.delete
# => 409 conflict
```

My issues is the following, I want to rename an image, to do that, I will retag it then ask to delete the old tag.

If an image has two tags (from the example above, when you do 

```
DELETE /images/repo1%2Fapp%3Alatest
=> [{"Untagged":"39e0e4c41dceeae8b6c7fa41339ebc00e36e6ac92701ff77945e305cf2d401d2"}]
````

it only destroys the tag, it can only be done by hand currently, which is not really beautiful.

``` ruby
Docker.connection.delete "/images/repo1%2Fapp%3Alatest"
```

**Comment by tlunter** [comment]
`#delete` or `#remove` can now take a name.
